//# sourceMappingURL=all.js.map
(function(b,a){function c(a){b.addEventListener("load",function(){new c.$b(a)})}b.B=c;c.extend=function(a,c){for(var f in c)a[f]=c[f]};c.extend(c,{h:function(a){this.extend(a)},ca:function(a){return function(c){return new a(c)}},id:function(c){return a.getElementById(c)},ready:function(a){b.addEventListener("load",a,!1)},v:function(c){return a.createElement(c)}});c.v.src=function(c,b){var f=a.createElement(c);f.setAttribute("src",b);return f};c.v.K=function(a){return c.v.src("img",a)};c.h.extend=
function(a,b){function f(){}var g,m=this,n=a.e||function(){m.apply(this,arguments)},l;f.prototype=m.prototype;n.prototype=new f;n.extend=c.h.extend;for(g in a)a.hasOwnProperty(g)&&(l=Object.getOwnPropertyDescriptor(a,g),Object.defineProperty(n.prototype,g,l));for(g in b)b.hasOwnProperty(g)&&(l=Object.getOwnPropertyDescriptor(b,g),Object.defineProperty(n,g,l));return n};c.h.prototype.extend=function(a){for(var c in a)this[c]=a[c]}})(this,this.document);
(function(b,a,c){var e=a.v("CANVAS"),d=a.ca;a.extend(a,{te:function(f){return Math.random()*f},Dc:function(f){return Math.random()*f|0},rf:function(f,a,c){var b=[],e;if(a)for(;a--;)for(b[a]=[],e=0;e<f;e++)b[a][e]=c;else for(;f--;)b.push(c);return b},canvas:function(f,c){var b=a.v("CANVAS");b.setAttribute("width",f);b.setAttribute("height",c);return b},pa:function(f){var c=typeof f;if("object"===c){if(null===f)return"null";if(f instanceof Array)return"array";if(f instanceof a.h)return"j5g3";if(f instanceof
b.HTMLElement||f instanceof b.Image)return"dom";if(f instanceof b.HTMLAudioElement)return"audio"}return c},Ja:function(f,a,c,b){return e.getContext("2d").createLinearGradient(f,a,c,b)},Hf:function(a,g,b,e){e===c&&(e=1);return"rgba("+a+","+g+","+b+","+e+")"},zf:function(a,g,b,e){e===c&&(e=1);return"hsla("+a+","+g+"%,"+b+"%,"+e+")"}});a.ga={eb:function(){},Xc:function(a){this.O(a);this.t(a);this.end(a)},hf:function(a){this.t(a)},hd:function(){var a=this.Ha;a.clearRect(0,0,this.width,this.height);this.O(a);
this.t(a);this.end(a);this.screen.clearRect(0,0,this.width,this.height);this.screen.drawImage(this.sa,0,0)},jd:function(){var a=this.Ha,c=this.I,b=this.H,e=this.J,d=this.G;0!==b&&0!==d&&(a.clearRect(c,e,b,d),this.O(a),this.t(a),this.end(a),this.screen.clearRect(c,e,b,d),this.screen.drawImage(this.sa,c,e,b,d,c,e,b,d),this.I=this.width,this.J=this.height,this.G=this.H=0)},lf:function(){var a=this.Ha;this.clearRect(0,0,this.canvas.width,this.canvas.height);this.O(a);this.t(a);this.end(a)},$e:function(a){a.drawImage(this.source,
this.x+this.b,this.y+this.a)},Za:function(a){a.drawImage(this.rd,0,0,this.width,this.height,this.x+this.b,this.y+this.a,this.width,this.height)}};a.X={Image:function(a){a.drawImage(this.source,this.b,this.a)},bb:function(a){var c=this.source;a.drawImage(c.K,c.x,c.y,c.Uc,c.Bc,this.b,this.a,this.width,this.height)},za:function(a){var c=this.frame,b=c;for(a.translate(this.b,this.a);(b=b.w)!==c;)b.A(a)},Text:function(a){a.fillText(this.text,this.b,this.a)},gd:function(a){for(var c=this.text.split("\n"),
b=0,e=c.length,d=0;b<e;b++)a.fillText(c[b],this.b,this.a+d),d+=this.ra},of:function(a){a.strokeText(this.text,this.b,this.a)},ld:function(a){a.fillText(this.text,this.b,this.a);a.strokeText(this.text,this.b,this.a)},ha:function(a){var c=this.map,b=c.length,e,d=this.fa,k,p;for(a.translate(this.b,this.a+b*this.ua);b--;)for(e=c[b].length,p=c[b],a.translate(e*this.W,-this.ua);e--;)a.translate(-this.W,0),(k=d[p[e]])&&k.A(a)},bf:function(a){var c=this.map,b=0,e,d=c.length,k=this.fa,p;e=(this.W/2|0)+this.offsetX;
var r=(this.ua/2|0)+this.offsetY,t,u;a.translate(this.b,this.a-r);for(t=e;b<d;b++)for(e=c[b].length,p=c[b],t=-t,a.translate(e*this.W-t,r);e--;)a.translate(-this.W,0),(u=k[p[e]])&&u.A(a)}};a.Za={Wc:function(f,c){var b=a.v("CANVAS"),e;b.width=f||this.width;b.height=c||this.height;e=b.getContext("2d",!1);e.translate(-this.x-this.b,-this.y-this.a);this.tc();this.A(e);this.rd=b;this.ic=this.A;this.A=a.ga.Za;return this},Oe:function(a,c){return a(c,e.getContext("2d"))}};a.Aa={eb:function(){return!1},ya:function(a,
c,b){b=b?b.product(this.p,this.x,this.y):this.p.sb(this.x,this.y);b.Ub(a,c);return b.x*b.x+b.y*b.y<=this.d*this.d?this:!1},za:function(a,c,b){var e=this.frame,d=e,k;for(b=b?b.product(this.p,this.x,this.y):this.p.sb(this.x,this.y);(d=d.F)!==e&&!(k=d.Fa(a,c,b)););return k},Rect:function(a,c,b){b=b?b.product(this.p,this.x,this.y):this.p.sb(this.x,this.y);b.Ub(a,c);return 0<b.x&&b.x<this.width&&0<b.y&&b.y<this.height?this:!1},ab:function(a,c,b){var e=this.T,d=this.Jb,k=0,p=e.length;b=b?b.product(this.p,
this.x,this.y):this.p.sb(this.x,this.y);for(b.Ub(a,c);k<p;k+=2)if(a=d[k]*(b.x-e[k])+d[k+1]*(b.y-e[k+1]),0<a)return!1;return this}};a.ed=a.h.extend({i:1,j:0,k:0,l:1,vb:1,zb:0,Na:1,Oa:1,e:function(a,b,e,d){a!==c&&(this.i=a,this.j=b,this.k=e,this.l=d)},Ae:function(a){this.vb=Math.cos(a);this.zb=Math.sin(a);return this.hb()},Be:function(a){this.Na=a;return this.hb()},Ce:function(a){this.Oa=a;return this.hb()},scale:function(a,c){this.Na=a;this.Oa=c;return this.hb()},hb:function(){this.i=this.Na*this.vb;
this.j=this.Na*this.zb;this.k=-this.Oa*this.zb;this.l=this.Oa*this.vb;return this},sb:function(f,c){return new a.ac(this.i,this.j,this.k,this.l,f||0,c||0)}});a.ac=a.h.extend({i:1,j:0,k:0,l:1,r:0,s:0,e:function(a,b,e,d,l,k){a!==c&&(this.i=a,this.j=b,this.k=e,this.l=d,this.r=l,this.s=k)},translate:function(a,c){this.r+=a;this.s+=c},multiply:function(a,c,b,e,d,k){var p=this.i,r=this.j,t=this.k,u=this.l;this.i=p*a+t*c;this.j=r*a+u*c;this.k=p*b+t*e;this.l=r*b+u*e;this.r+=p*d+t*k;this.s+=r*d+u*k;return this},
clone:function(){return a.ke().multiply(this.i,this.j,this.k,this.l,this.r,this.s)},inverse:function(){var a=this.clone(),c=this.i*this.l-this.j*this.k;a.i=this.l/c;a.j=this.j/-c;a.k=this.k/-c;a.l=this.i/c;a.r=(this.l*this.r-this.k*this.s)/-c;a.s=(this.j*this.r-this.i*this.s)/c;return a},product:function(a,c,b){return this.clone().multiply(a.i,a.j,a.k,a.l,a.r||c||0,a.s||b||0)},reset:function(){this.i=1;this.k=this.j=0;this.l=1;this.s=this.r=0;return this},Nf:function(a,c){this.x=this.i*a+this.k*c+
this.r;this.y=this.j*a+this.l*c+this.s;return this},Ub:function(a,c){var b=this.i*this.l-this.j*this.k;this.x=(this.l*a-this.k*c+this.k*this.s-this.l*this.r)/b;this.y=(-this.j*a+this.i*c+this.j*this.r-this.i*this.s)/b;return this}});a.g=a.h.extend({source:null,w:null,F:null,parent:null,p:null,x:0,y:0,b:0,a:0,width:null,height:null,mc:0,set rotation(a){this.p.Ae(this.mc=a)},get rotation(){return this.mc},set U(a){this.p.Be(a)},get U(){return this.p.Na},set V(a){this.p.Ce(a)},get V(){return this.p.Oa},
alpha:1,qc:null,stroke:null,fill:null,font:null,La:null,Hb:null,Ib:null,Ic:null,vf:!0,e:function(f){this.p=new a.ed;this.extend(f)},O:function(a){var c=this.p;a.save();1!==this.alpha&&(a.globalAlpha*=this.alpha);null!==this.fill&&(a.fillStyle=this.fill);null!==this.stroke&&(a.strokeStyle=this.stroke);null!==this.font&&(a.font=this.font);null!==this.qc&&(a.globalCompositeOperation=this.qc);null!==this.La&&(a.lineWidth=this.La);null!==this.Hb&&(a.lineCap=this.Hb);null!==this.Ib&&(a.lineJoin=this.Ib);
null!==this.Ic&&(a.miterLimit=this.Ic);a.transform(c.i,c.j,c.k,c.l,this.x,this.y)},end:function(a){a.restore()},A:a.ga.Xc,wb:null,R:function(){this.parent.R(this)},update:null,remove:function(){this.parent&&(this.F.w=this.w,this.w.F=this.F,this.parent=this.F=null);return this},align:function(a,c){c=c||this.parent;switch(a){case "center":this.x=c.width/2;break;case "left":this.x=0;break;case "right":this.x=c.width-this.width;break;case "middle":this.y=c.height/2;break;case "center middle":this.L(c.width/
2,c.height/2);break;case "origin":this.L(-this.width/2,-this.height/2);break;case "origin top":this.L(-this.width/2,-this.height);break;case "origin bottom":this.L(-this.width/2,0)}return this},L:function(a,c){this.x=a;this.y=c;return this},size:function(a,c){this.width=a;this.height=c;return this},move:function(a,c){this.x+=a;this.y+=c;return this},visible:function(){return 0<this.alpha},stretch:function(a,c){return this.scale(a/this.width,c/this.height)},Lf:function(){return a.clip({width:this.width,
height:this.height}).add(this)},sc:a.Za.Wc,tc:function(){this.ic&&(this.A=this.ic)},set:function(a){this.extend(a);return this},Fa:a.Aa.Rect,scale:function(a,c){b.isNaN(a)||(this.U=a);b.isNaN(c)||(this.V=c);return this},rotate:function(a){this.rotation+=a;return this}});a.Image=a.g.extend({e:function(c){switch(a.pa(c)){case "string":c={source:a.id(c)};break;case "dom":c={source:c}}a.g.call(this,c);this.source&&this.Fe(this.source)},t:a.X.Image,zd:function(c){return"string"===typeof c?a.id(c):c},Fe:function(a){this.source=
this.zd(a);null===this.width&&(this.width=this.source.naturalWidth||this.source.width);null===this.height&&(this.height=this.source.naturalHeight||this.source.height)}});a.Text=a.g.extend({text:"",ra:null,pf:null,Sd:function(a){var c=this.Hc();"left"===a?this.b=0:"center"===a?this.b=-c/2:"right"===a&&(this.b=-c);return this},e:function(c){"string"===typeof c&&(c={text:c});a.g.call(this,c);null===this.ra&&this.Hc()},wb:a.X.Text,t:a.X.Text,Hd:function(c,b){var e=(""+c.text).split("\n"),d,l=e.length,
k=0;a:{d=c;do{if(null!==d.font){d=d.font;break a}if(d instanceof a.cb)break}while(d=d.parent);d=void 0}c.O(b);d&&(b.font=d);for(;l--;)d=b.measureText(e[l]),d.width>k&&(k=d.width);null===c.ra&&(c.ra=parseInt(b.font,10));c.end(b);return k},ub:a.g.prototype.O,O:function(a){a.textBaseline="top";this.ub(a)},Hc:function(){return a.Za.Oe(this.Hd,this)}});a.ad=a.g.extend({Cc:"",e:function(c){"string"===typeof c&&(c={Cc:a.v(c).innerHTML});a.g.apply(this,[c])}});a.u=a.g.extend({N:null,ja:0,length:null,Pb:!0,
Ie:1,e:function(c){a.g.call(this,c);this.N=[];this.nc();null!==this.Z&&this.Z()},R:function(a){this.parent.R(a||this)},Z:null,update:function(){var a=this.frame,c=a;for(this.Vb&&this.Vb();(c=c.w)!==a;)null!==c.update&&c.update();this.Pb&&((this.ja+=this.Ie)>=this.length&&(this.ja=0),this.frame=this.N[this.ja|0])},frame:null,t:a.X.za,stop:function(){this.Pb=!1;return this},play:function(){this.Pb=!0;return this},add:function(c){switch(a.pa(c)){case "function":c=new a.Xb(c);break;case "string":c=new a.Image({source:c});
break;case "array":for(var b=0;b<c.length;b++)this.add(c[b]);return this;case "dom":case "object":c=new a.Image(c);break;case "undefined":case "null":throw"Trying to add undefined object to clip.";}return this.oc(c)},oc:function(a){var c=this.frame;a.parent&&a.remove();c.F.w=a;a.F=c.F;a.w=c;a.parent=this;c.F=a;return this},nc:function(a){var c={};c.F=c.w=c;this.N.push(c);this.go((this.length=this.N.length)-1);return a?this.add(a):this},Bf:function(){return this.frame.w===this.frame},we:function(a){a=
a===c?this.ja:a;this.N.splice(a,1);this.go(0<a?a-1:0);this.length=this.N.length;return this},go:function(a){this.frame=this.N[this.ja=a];return this},ib:function(a){for(var c=this.N.length,b,e;c--;)for(e=b=this.N[c];(e=e.w)!==b;)a(e);return this},xf:function(a){for(var c=this.frame,b=c,e;(b=e=b.w)!==c;)for(;(e=e.w)!==c;)a(b,e)},qf:function(a){return this.ib(function(c){c.align&&c.align(a)})},Fa:a.Aa.za});a.cb=a.u.extend({canvas:null,Ha:null,screen:null,sa:null,Jf:!1,background:!1,ba:!1,I:0,J:0,H:0,
G:0,Cd:function(){if(!1===this.ba)return this.ba=b.document.body;var c=this.ba=a.v("DIV");c.className="j5g3-stage";b.document.body.appendChild(c);return c},Bd:function(){var c=this.ba||this.Cd();this.canvas||(this.canvas=a.canvas(this.width,this.height),this.background?c.insertBefore(this.canvas,c.firstChild):c.appendChild(this.canvas));this.sa=a.v("CANVAS")},Dd:function(){this.Ha=this.sa.getContext("2d");this.screen=this.canvas.getContext("2d")},e:function(c){a.u.call(this,c);this.Bd();this.ye(this.width||
this.canvas.clientWidth||640,this.height||this.canvas.clientHeight||480);this.Dd()},he:function(c){var b;"string"===typeof c&&(c={canvas:a.id(c)});a.extend(b={width:this.width,height:this.height,ba:this.ba},c);c=new a.cb(b);c.A=a.ga.jd;this.add(c);return c},R:function(a){if(a===c)this.I=this.J=0,this.G=this.height,this.H=this.width;else{var b=a.x+a.b,e=a.y+a.a;b<this.I&&(this.H+=this.I-b,this.I=b);e<this.J&&(this.G+=this.J-e,this.J=e);b+a.width>this.I+this.H&&(this.H=b+a.width-this.I,this.I+this.H>
this.width&&(this.H=this.width-this.I));e+a.height>this.J+this.G&&(this.G=e+a.height-this.J,this.J+this.G>this.height&&(this.G=this.height-this.J))}},ye:function(a,c){if(0===a||0===c)throw Error("Invalid stage resolution: "+a+"x"+c);this.H=this.canvas.width=this.sa.width=a;this.G=this.canvas.height=this.sa.height=c;return this.size(a,c)},A:a.ga.hd});a.Ca=a.g.extend({aa:!1,repeat:Infinity,duration:100,Y:null,target:null,D:null,Ta:0,Nc:null,nb:null,e:function(c){c instanceof a.h&&(c={target:c});this.update=
this.start;a.g.apply(this,[c])},A:a.ga.eb,pause:function(){this.jc=this.update;this.update=null;return this},ze:function(){this.update=this.jc?this.jc:this.start;return this},Qc:function(){this.repeat-=1;this.Xa=this.Ta=0;return this},Gf:function(){this.Ta=0;return this.stop().start()},stop:function(){this.pause().Qc();this.Nc&&this.Nc();return this},Wd:function(a){return a},pc:function(a,c){return this.Y[a]+this.Wd(c)*(this.D[a]-this.Y[a])},Ld:a.g.prototype.remove,remove:function(){this.nb&&this.nb();
this.Ld()},sd:function(){var a=this.target,c;this.duration===this.Ta&&(this.Xa=1);for(c in this.D)a[c]=this.pc(c,this.Xa);this.Ta<this.duration?(this.Ta++,this.Xa+=this.Pe):this.aa?this.remove():this.repeat?this.Qc():this.stop()},start:function(){var a=this.D,c,b=this.target;if(null===this.Y)for(c in this.Y={},a)this.Y[c]=b[c];this.Pe=1/this.duration;this.Xa=0;this.update=this.sd;return this},Fa:a.Aa.eb});a.bb=a.g.extend({e:function(c){a.g.call(this,c);if(!this.source)throw Error("Invalid source property for Sprite");
null===this.width&&(this.width=this.source.Uc);null===this.height&&(this.height=this.source.Bc)},t:a.X.bb});a.kd=a.h.extend({width:null,height:null,gb:null,e:function(c){switch(a.pa(c)){case "string":case "dom":case "j5g3":c={source:c}}a.h.call(this,c)},set source(c){switch(a.pa(c)){case "string":case "dom":c=new a.Image(c);break}if(!c)throw Error("Invalid source for Spritesheet.");null===this.width&&c&&(this.width=c.width);null===this.height&&c&&(this.height=c.height);this.Md=c;this.gb=[]},get source(){return this.Md},
select:function(a){var c=[];this.ib(a,function(a){c.push(a)});return c},ib:function(a,c){for(var b=0,e=a.length;b<e;b++)c(this.Qa(a[b]));return this},clip:function(c){var b=a.clip().we(),e=0,d=0;this.ib(c,function(a){b.nc(a);a.width>e&&(e=a.width);a.height>d&&(d=a.height)});return b.size(e,d).go(0)},push:function(a,c,b,e){this.slice(a,c,b,e);return this},slice:function(a,c,b,e){return this.gb.push({width:b,height:e,source:{K:this.source.source,x:a,y:c,Uc:b,Bc:e}})-1},tf:function(a,c,b,e){return this.Qa(this.slice(a,
c,b,e))},ce:function(a,c,b){b=b||0;var e=2*b,d=this.width/a-e|0,k=this.height/c-e|0,p,r;for(p=0;p<c;p++)for(r=0;r<a;r++)this.slice(r*(d+e)+b,p*(k+e)+b,d,k);return this},Qa:function(c){return new a.bb(this.gb[c])},fa:function(){for(var a=0,c=this.gb.length,b=[];a<c;a++)b.push(this.Qa(a));return b},map:function(c,b){return new a.ha({fa:this.fa(),W:c,ua:b})}});a.$c=a.u.extend({e:function(c){a.u.apply(this,[c])},source:a.u,Ud:function(){this.Gd--?null!==this.ec&&this.ec():this.remove()},ie:10,Kc:null,
count:1,He:function(){var a=new this.source;a.Gd=this.ie;a.ec=a.update;a.update=this.Ud;return a},ud:function(){var a=this.He();this.oc(a);this.Kc&&this.Kc(a)},Vb:function(){for(var a=this.count;a--;)this.ud()}});a.ha=a.g.extend({fa:null,map:null,W:0,ua:0,offsetX:0,offsetY:0,e:function(c){a.g.apply(this,[c]);null===this.map&&(this.map=[])},Mf:function(a,c){var b=(this.W/2|0)+this.offsetX;return{x:(a*this.W-(c%2?0:-b)|0)-this.b,y:(c*((this.ua/2|0)+this.offsetY)|0)-this.a}},t:a.X.ha});a.Xb=a.h.extend({Ad:a.h,
update:null,A:a.ga.eb,e:function(c){"function"===a.pa(c)&&(c={update:c});this.Ad(c)},remove:a.g.prototype.remove},{rotate:function(a){return function(){a.rotation=6.1>a.rotation?a.rotation+.1:0}}});a.$b=a.h.extend({version:"0.9.0",tb:31,yb:null,fc:null,lc:0,gc:0,paused:!0,Sc:function(){var a=this;a.uc();a.yb=function(){a.kc()};a.kc();a.fc=function(){a.wd()};a.gc=b.setInterval(a.fc,a.tb);a.paused=!1;return a},uc:function(){b.clearInterval(this.gc);b.cancelAnimationFrame(this.lc)},oa:function(){this.pause();
this.oe&&this.oe()},kc:function(){this.m.A();this.lc=b.requestAnimationFrame(this.yb)},wd:function(){this.m.update()},Tb:function(){},e:function(d){"function"===typeof d&&(d={Tb:d});d===c&&(d={});e.style.display="none";e.setAttribute("id","j5g3-cache");b.document.body.appendChild(e);a.h.apply(this,[d]);this.Ra||(this.Ra={});this.Ra.canvas||(this.Ra.canvas=a.id("screen"));this.m||(this.m=new a.cb(this.Ra));this.Tb(a,this)},pause:function(){this.uc();this.yb=function(){};this.paused=!0},ze:function(){this.paused&&
this.Sc()},set $d(a){this.tb=1E3/a},get $d(){return 1E3/this.tb},Af:function(c,b){var d,n;switch(a.pa(c)){case "string":d=a.id(c);break;case "dom":d=c;break;case "j5g3":d=c.source}return d?(e.width=d.width,e.height=d.height,n=e.getContext("2d"),n.drawImage(d,0,0),n.getImageData(0,0,d.width,d.height)):this.m.Ha.createImageData(c||this.m.canvas.width,b||this.m.canvas.height)}});a.Ye=function(){function a(c,b){e["EaseIn"+c]=b;e["EaseOut"+c]=function(a){return 1-b(1-a)};e["EaseInOut"+c]=function(a){return.5>
a?b(2*a)/2:b(-2*a+2)/-2+1}}var c={},b,e={};["Quad","Cubic","Quart","Quint","Expo"].forEach(function(a,b){c[a]=function(a){return Math.pow(a,b+2)}});c.mf=function(a){return 1-Math.cos(a*Math.PI/2)};c.We=function(a){return 1-Math.sqrt(1-a*a)};c.Ze=function(a){return 0===a||1===a?a:-Math.pow(2,8*(a-1))*Math.sin((80*(a-1)-7.5)*Math.PI/15)};c.Te=function(a){return a*a*(3*a-2)};c.Ve=function(a){for(var c,b=4;a<((c=Math.pow(2,--b))-1)/11;);return 1/Math.pow(4,3-b)-7.5625*Math.pow((3*c-2)/22-a,2)};for(b in c)a(b,
c[b]);e.ef=function(a){return a};e.nf=function(a){return-Math.cos(a*Math.PI)/2+.5};return e}();a.action=d(a.Xb);a.clip=d(a.u);a.K=d(a.Image);a.Qa=d(a.bb);a.rb=d(a.kd);a.text=d(a.Text);a.m=d(a.cb);a.me=function(){var c=new a.Text("Drag Left/Right/Down to move.\n\nDrag Up to Rotate.\n\nFlick Down to Hard Drop.");c.t=a.X.gd;return c};a.ke=function(){return new a.ac(void 0,void 0,void 0,void 0,void 0,void 0)};a.va=d(a.Ca);a.yf=d(a.$c);a.map=d(a.ha);a.Cc=d(a.ad);a.Xd=d(a.$b)})(this,this.B);
(function(b,a){a.dd=a.h.extend({Zc:{IMG:"load",AUDIO:"canplaythrough",SCRIPT:"load"},$:null,Vd:250,Qb:0,start:null,length:0,Mc:null,ob:null,Nb:null,e:function(c){a.h.apply(this,[c]);this.$={};this.start=new Date},cc:function(){var a,e=0,d=0,f=this;for(a in this.$)d++,this.$.hasOwnProperty(a)&&this.$[a].ready&&e++;this.Qb=e?e/d:0;this.Mc&&this.Mc(this.Qb);d===e?this.Nb&&this.Nb():this.Nd=b.setTimeout(function(){f.cc()},this.Vd)},P:function(c,e){var d=this,f=this.$[e],g;f?f=f.P:(f=a.v(c),this.$[e]=
g={P:f},f.addEventListener(this.Zc[c],function(){g.ready=!0;d.ob&&d.ob(g)},!1),f.addEventListener("error",function(){g.ready=!0;b.console.warn("Could not load asset: "+e)},!1),f.setAttribute("src",e),this.length++);return f},qa:function(a){return this.P("IMG",a)},audio:function(c){var b=c.split(".").pop();a.Sa.audio[b]||(c=c.replace(new RegExp("\\."+b+"$"),"."+a.Sa.audio.se));return this.P("AUDIO",c)},data:function(a,e){var d=this,f=new b.XMLHttpRequest,g=this.$[a];g||(g=this.$[a]={source:a,Ff:f},
f.onreadystatechange=function(){4===f.readyState&&(g.ready=!0,g.ue=f.responseText,e&&e(g),d.ob&&d.ob(f))},f.open("GET",a),f.send());return g},ge:function(a){return this.data(a,function(a){a.ge=JSON.parse(a.ue)})},If:function(a){a=this.P("SCRIPT",a);b.document.head.appendChild(a);return a},ready:function(a){a&&(this.Nb=a);this.cc()},oa:function(){b.clearTimeout(this.Nd)}});a.je=a.ca(a.dd)})(this,this.B);
(function(b){b.$a=b.h.extend({Vc:null,Yb:null,Kb:0,Lb:0,Ob:0,length:0,Ua:0,Va:0,0:null,1:null,2:null,3:null,4:null,5:null,6:null,Pc:null});b.$a.ya=b.$a.extend({Pc:function(a,c){var b=a.d+c.d,d=a.x+a.d+a.b,f=a.y+a.d+a.a,g=d-c.d-c.b-c.x,m=f-c.d-c.a-c.y,n=g*g+m*m;if(this.na=b*b>n)return n=Math.sqrt(n),this.Vc=a,this.Yb=c,this.Kb=g/n,this.Lb=m/n,this.Ob=b-n,this[0]=d-g/2,this[1]=f-m/2,!0}});b.$a.Wb=b.$a.extend({Pc:function(a,c){var b=a.x+a.b,d=c.x+c.b,f=a.y+a.a,g=c.y+c.a,m=b+a.width,n=d+c.width,l=f+a.height,
k=g+c.height,p,r;if(this.na=!(d>=m||n<=b||g>=l||k<=f))return this.Yb=c,p=this.Ua=n/2-m/2,r=this.Va=k/2-l/2,this[0]=Math.max(b,d),this[1]=Math.max(f,g),this[2]=Math.min(m,n),this[3]=Math.min(l,k),this[2]-this[0]<this[3]-this[1]?(this.Kb=0>p?-1:1,this.Lb=0,this.Ob=0>p?this[2]-b:m-this[0]):(this.Lb=0>r?-1:1,this.Kb=0,this.Ob=0>r?this[3]-f:l-this[1]),this}});b.Zb={ya:function(a){var c=this.d+a.d,b=this.x+this.d+this.b-a.d-a.b-a.x;a=this.y+this.d+this.a-a.d-a.a-a.y;return c*c>b*b+a*a},Wb:function(a){var c=
this.y+this.height,b=a.x+a.width,d=a.y+a.height;return!(a.x>this.x+this.width||b<this.x||a.y>c||d<this.y)},za:function(a){var c=this.frame,b=c,d=!1;for(a={x:a.x-this.x,y:a.y-this.y,width:a.width,height:a.height};(b=b.F)!==c&&!(d=b.na&&b.na(a)););return d}};b.g.prototype.na=b.Zb.Wb;b.u.prototype.na=b.Zb.za})(this.B);
(function(b,a){b.M=b.g.extend({shape:null,red:a,green:a,blue:a,vc:"fill",xb:a,hc:a,bc:a,La:null,e:function(a){b.g.apply(this,[a])},ub:b.g.prototype.O,O:function(a){if(this.red!==this.xb||this.blue!==this.bc||this.green!==this.hc)this[this.vc]="rgb("+Math.floor(this.red)+","+Math.floor(this.green)+","+Math.floor(this.blue)+")",this.xb=this.xb,this.hc=this.green,this.bc=this.blue;this.ub(a)},pb:function(){},t:function(a){a.beginPath();this.pb(a);a.closePath();a.fill();a.stroke()}});b.ya=b.M.extend({shape:"circle",
d:0,e:function(a){"number"===typeof a&&(a={d:a});b.M.apply(this,[a])},pb:function(a){a.arc(this.d+this.b,this.d+this.a,this.d,0,2*Math.PI,!1)},Fa:b.Aa.ya});b.bd=b.M.extend({Qe:0,Re:0,pb:function(a){a.moveTo(this.b,this.a);a.lineTo(this.Qe,this.Re)}});b.ab=b.M.extend({shape:"polygon",T:null,Jb:null,e:function(a){b.M.apply(this,[a]);null===this.T&&(this.T=[]);null===this.Jb&&this.Td()},normalize:function(a){var b=Math.sqrt(a[0]*a[0]+a[1]*a[1]);a[0]/=b;a[1]/=b;return a},Td:function(){for(var a=0,b,d=
this.T,f=d.length,g=[],m=[0,0];a<f;a+=2)b=a+2<f?a+2:0,m[0]=d[b]-d[a],m[1]=d[b+1]-d[a+1],this.normalize(m),g.push(m[1],-m[0]);this.Jb=g},pb:function(a){var b=2,d=this.T,f=d.length;for(a.moveTo(d[0],d[1]);b<f;b+=2)a.lineTo(d[b],d[b+1])},Fa:b.Aa.ab},{create:function(a,e){var d=2*Math.PI/a,f=d;for(e.T=[];a--;)e.T.push(Math.cos(f)*e.d,Math.sin(f)*e.d),f+=d;return new b.ab(e)}});b.Rect=b.M.extend({shape:"polygon",e:function(a){b.M.apply(this,[a]);null===this.width&&(this.height=this.width=2*this.d)},t:function(a){a.fillRect(this.b,
this.a,this.width,this.height);a.strokeRect(this.b,this.a,this.width,this.height)}});b.Yc=b.M.extend({shape:"circle",Hb:"round",Ib:"round",vc:"stroke",e:function(a){"number"===typeof a&&(a={La:a});b.M.apply(this,[a])},t:function(a){a.strokeRect(0,0,1,1)}});b.Ef=b.ca(b.ab);b.sf=b.ca(b.ya);b.Df=b.ca(b.bd);b.wf=b.ca(b.Yc);b.rect=b.ca(b.Rect)})(this.B);
(function(b,a){var c=a.v("audio"),e=["wav","mp3","ogg"],d=["audio/wav","audio/mpeg","audio/ogg"];Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}});b.HTMLAudioElement||(b.HTMLAudioElement=b.Se);b.requestAnimationFrame||(b.requestAnimationFrame=b.mozRequestAnimationFrame||b.msRequestAnimationFrame||function(a){return b.setTimeout(a,1E3/60)});b.cancelAnimationFrame||(b.cancelAnimationFrame=b.mozCancelAnimationFrame||b.msCancelAnimationFrame||
function(a){b.clearTimeout(a)});a.Sa={audio:{},Ne:"ontouchstart"in b.document};c&&c.canPlayType&&e.forEach(function(b,e){a.Sa.audio[b]=c.canPlayType(d[e]);a.Sa.audio[b]&&(a.Sa.audio.se=b)})})(this,this.B);(function(b,a){b.o=function(a){return new b.o.cd(a)};b.extend(b.o,{ia:{},cd:b.h.extend({x:0,y:0,wc:0,xc:0,U:1,V:1,C:null,element:null,interval:60,de:null,le:!1,disabled:!1,e:function(c){var e=this;if("string"===typeof c||"object"===typeof c&&c.tagName)c={element:c};b.h.call(this,c);null===this.element?this.element=a.document:"string"===typeof this.element&&(this.element=b.id(this.element));e.C={};e.Oc=function(){e.Kd()};e.Ga=function(a){e.td(a)};a.addEventListener("resize",this.Ga);a.addEventListener("scroll",
this.Ga);this.de=a.setInterval(this.Oc,this.interval);this.Ga();for(var d in b.o.ia)e.C[d]=new b.o.ia[d](e)},Le:function(c){var b=this;b.disabled=!0;a.setTimeout(function(){b.disabled=!1},c)},q:function(a,b){if(!this.disabled&&(b.Cf=this,b.name=a,(!this.Lc||!1!==this.Lc(b))&&this[a]))return b.preventDefault(),this[a](b)},td:function(){var c=this.element;c.getBoundingClientRect?(c=c.getBoundingClientRect(),this.Bb=a.scrollX+c.left||0,this.Cb=a.scrollY+c.top||0):(this.Bb=c.clientLeft||0,this.Cb=c.clientTop||
0)},Kd:function(){if(!1===this.disabled)for(var a in this.C)this.C[a].update()},Rb:function(a,b){a=a*this.U-this.Bb;b=b*this.V-this.Cb;this.wc=a-this.x;this.xc=b-this.y;this.x=a;this.y=b},oa:function(){this.disable();a.removeEventListener("scroll",this.Ga);a.removeEventListener("resize",this.Ga);a.clearInterval(this.Oc)},enable:function(){this.disabled=!1;for(var a in this.C)this.C[a].enable()},disable:function(){this.disabled=!0;for(var a in this.C)this.C[a].disable()}}),Ba:b.h.extend({Q:null,P:null,
enabled:!1,Ea:null,Da:null,e:function(a){this.Q={};this.c=a;this.P=a.element;this.enable();a.le&&this.Id()},update:function(){},ka:function(a,b){var d=b.bind(this);this.Q[a]=d;this.P.addEventListener(a,d)},la:function(a){this.P.removeEventListener(a,this.Q[a])},enable:function(){this.enabled||(this.Ea(),this.enabled=!0);return this},disable:function(){this.enabled&&(this.Da(),this.enabled=!1);return this},oa:function(){this.disable();for(var a in this.c.C)if(this.c.C[a]===this){delete this.c.C[a];
break}}})})})(this.B,this);
(function(b){b.o.ia.fd=b.o.Ba.extend({wa:1,xa:1,Bb:0,Cb:0,Db:!0,fb:function(a){this.c.Rb(a.pageX,a.pageY)},dc:function(a){var c={0:"buttonY",1:"buttonX",2:"buttonA"}[a.button];this.fb(a);this.c.q(c,a);this.c.q("button",a);return!1},Id:function(){this.Db=!1},Jd:function(a){this.Db&&(this.fb(a),(Math.abs(this.c.wc)>this.wa||Math.abs(this.c.xc)>this.xa)&&this.c.q("move",a))},Ea:function(){this.ka("mousemove",this.Jd);this.ka("click",this.dc);this.ka("contextmenu",this.dc)},Da:function(){this.la("mousemove");
this.la("click");this.la("contextmenu")}})})(this.B,this);
(function(b){b.o.ia.Touch=b.o.Ba.extend({wa:35,xa:35,jb:80,zc:300,Me:300,touches:null,Jc:"linear",d:25,Ab:0,fb:function(a){this.c.Rb(a.pageX,a.pageY)},Eb:function(a,c){for(var b=a.changedTouches,d=b.length,f,g;d--;)g=b[d].identifier,f=this.touches[g]||(this.touches[g]={id:g}),f.Fb=a,f.Ne=b[g],this.fb(b[d]),c(a,b[d],f,this)},update:function(){var a=this.touches,c;for(c in a)this.c.Rb(a[c].kb,a[c].lb),this.c.q("buttonY",a[c].Fb),this.c.q("button",a[c].Fb)},od:function(a,c,b,d){c=d.c.x;var f=d.c.y,g=
c-b.kb,m=f-b.lb,n=Date.now()-b.Tc,l;g<-d.wa?(b.kb=c,l="left"):g>d.wa&&(b.kb=c,l="right");m<-d.xa?(b.lb=f,l="up"+(l?"_"+l:"")):m>d.xa&&(b.lb=f,l="down"+(l?"_"+l:""));(d.direction=l)&&n>d.zc&&(d.c.q(l,a),d.c.q("move",a))},pd:function(a,c,b,d){var f=d.c.x,g=d.c.y;c=b.Ua-f;var m=b.Va-g,f=f-b.qe;b=g-b.re;(c>d.wa||c<-d.wa)&&(m>d.xa||m<-d.xa)&&(a.Ab=Math.atan2(b,f),d.c.q("move",a))},Pd:function(a){this.Eb(a,"linear"===this.Jc?this.od:this.pd)},vd:function(a,c){var b=this.c.x-c.Ua,d=this.c.y-c.Va,f;b<-this.jb?
f="buttonY":b>this.jb&&(f="buttonA");d<-this.jb?f="buttonX":d>this.jb&&(f="buttonB");f?this.c.q(f,a):this.direction&&(this.c.q(this.direction,a),this.c.q("move",a))},Ee:function(a){a.qe=a.Ua-Math.cos(this.Ab)*this.d;a.re=a.Va-Math.sin(this.Ab)*this.d},qd:function(a,c,b,d){b.Tc=Date.now();b.Fb=a;b.Ua=b.kb=d.c.x;b.Va=b.lb=d.c.y;"radial"===d.Jc&&d.Ee(b)},Qd:function(a){this.direction=!1;this.Eb(a,this.qd)},nd:function(a,c,b,d){c=Date.now()-b.Tc;!d.direction&&c<d.Me?d.c.q("buttonY",a):c<d.zc&&d.vd(a,
b);delete d.touches[b.id]},Od:function(a){this.Eb(a,this.nd)},Ea:function(){this.ka("touchmove",this.Pd);this.ka("touchstart",this.Qd);this.ka("touchend",this.Od);this.touches={}},Da:function(){this.la("touchmove");this.la("touchstart");this.la("touchend")}})})(this.B,this);
(function(b,a){var c=a.document,e={32:"buttonB",13:"buttonY",16:"buttonX",17:"buttonA",37:"left",38:"up",39:"right",40:"down",105:"up_right",103:"up_left",99:"down_right",97:"down_left"};b.o.ia.df=b.o.Ba.extend({Ka:null,keys:null,Ed:function(a){this.keys[a.keyCode]=a;this.Ka[a.keyCode]&&a.preventDefault()},e:function(a){this.keys={};b.o.Ba.call(this,a);null===this.Ka&&b.extend(this.Ka={},e)},Fd:function(a){this.keys[a.keyCode]=!1},update:function(){var a,c,b;for(b in this.Ka)if(c=this.keys[b])a=this.Ka[b],
this.c.q(a,c),32<b&&(c.direction=a,this.c.q("move",c)),this.c.q("button",c)},Ea:function(){this.keys={};this.Q.Ec=this.Ed.bind(this);this.Q.Fc=this.Fd.bind(this);c.addEventListener("keydown",this.Q.Ec);c.addEventListener("keyup",this.Q.Fc)},Da:function(){this.keys={};c.removeEventListener("keydown",this.Q.Ec);c.removeEventListener("keyup",this.Q.Fc)}})})(this.B,this);(function(b,a){a.navigator.Of&&(b.o.ia.cf=b.o.Ba.extend({Ea:function(){},Da:function(){}}))})(this.B,this);(function(b){b.ae={kf:{uf:b.v.K("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPxJREFUeNqckzEKwjAUhlPB6hm8QUd1EbpVRHAS0eO0N3DuIVx0EaSoHbtoR2/gFVorGv/oSwnRIfHBlwba/Pnf63sO53zDGLuCNdgxs/DAAvQZBCL+iQfIwRL4gGl4IAQpKOlM7IgXUMpBS7nhDs4gARUIwAC0lW+eYCLVU24fwi1rkNqe2cfhvSr5FRa3V7JOapGOFgKZPNf4smQWidyoAq6FQPVLYGQhENQ7ysWnwphGQYWvHcxA08KBaKi5mkLwRx8MxSJaeYznVqtHCTL6My7Vp6e5vIGuyD+mvEpq6VDmp+HToOU0eCIih8b5BFbgYmhfuJ6CzkuAAQBw8IUZ2uqgnAAAAABJRU5ErkJggg=="),
Kf:b.v.K("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAO5JREFUeNpi/P//PwMeEA3EL4B4Ly4FjAQM2APEH4E4GKcKkAE4sD0Q/wXi30BshEsdEx7b04AYJM8CxDmkukANiL/+R4DPQKyCTS0oDJKA5kgBsTgSlodiZPAIiB8C8WsgfgnEr4D4KcgUbyB+/Z908AKInWBOMQXiOyRovgXE+uAYRPKPIhCfIULzKSCWg+lDDxRhIL6LR/NDIBbEF42fgVgIT9SKgiIOWQDdAEsgFsBjACcQW+AzwADNNZ1A3AjE75DEDfElpPnQ5Lscmphg4rJAPAeIfwHxKmQ96AYsBGJnPPkDFN0LkMUAAgwAJMvR40MRRPUAAAAASUVORK5CYII=")},jf:{Xe:function(){}},
Ue:{af:function(){}},Text:{gf:function(a){var c=this.stroke||this.fill||a.fillStyle,b=this.La||a.lineWidth;a.strokeStyle=c;a.globalAlpha=.2;a.lineWidth=b+10;a.strokeText(this.text,this.b,this.a);a.globalAlpha=.4;a.lineWidth=b+5;a.strokeText(this.text,this.b,this.a);a.globalAlpha=1;a.lineWidth=b;a.strokeText(this.text,this.b,this.a);a.globalCompositeOperation="lighter";a.fillStyle=c;a.fillText(this.text,this.b,this.a)},ff:function(a){this.wb(a);a.scale(1,-1);var c=this.a;this.a-=2*this.ra;this.Ja||
(this.Ja=a.createLinearGradient(-this.b,this.a,-this.b,this.a+this.ra),this.Ja.addColorStop(1,this.fill||a.fillStyle),this.Ja.addColorStop(0,"transparent"));a.fillStyle=this.Ja;this.wb(a);this.a=c}},Ya:{Yd:function(a){return new b.Ca({target:a,duration:30,aa:!0,Y:{alpha:0},D:{alpha:1}})},Zd:function(a){return new b.Ca({target:a,aa:!0,duration:30,D:{alpha:0}})},expand:function(a,c){c=c||1.5;return new b.Ca({target:a,aa:!0,duration:30,D:{U:a.U+c,V:a.V+c}})},Sb:function(a){a=new b.Ca({target:a,d:3,duration:10,
aa:!0,D:{x:a.x,y:a.y}});a.pc=function(a,e){return 1===e?this.D[a]:this.Y[a]-this.d+b.te(2*this.d)};return a}}}})(this.B);var h=window.B,q=h.je(),s=h.ae,v=q.qa("resources/background.jpg"),w=q.qa("resources/blocks-ss.png"),x=q.qa("resources/logo.png"),y=q.qa("resources/play.png"),z=q.qa("resources/score.png"),A=q.qa("resources/gameover.png"),C={pop:q.audio("resources/pop.ogg"),slide:q.audio("resources/slide.ogg"),rotate:q.audio("resources/rotate.ogg"),line:q.audio("resources/line.ogg")},E=h.ha.extend({md:[3,4,3,2,3,3,3],W:48,ua:48,Rc:1,ma:0,xd:function(b,a){switch(b){case 0:return[[[a],[a],[a,a]],[[a,a,a],[a]],[[0,a,
a],[0,0,a],[0,0,a]],[[],[0,0,a],[a,a,a]]];case 1:return[[[0,a],[0,a],[0,a],[0,a]],[[],[a,a,a,a],[],[]],[[0,0,a],[0,0,a],[0,0,a],[0,0,a]],[[],[],[a,a,a,a],[]]];case 2:return[[[a],[a,a],[a]],[[a,a,a],[0,a],[]],[[0,0,a],[0,a,a],[0,0,a]],[[],[0,a],[a,a,a]]];case 3:return[[[a,a],[a,a]],[[a,a],[a,a]],[[a,a],[a,a]],[[a,a],[a,a]]];case 4:return[[[0,a],[0,a],[a,a]],[[a],[a,a,a],[]],[[0,a,a],[0,a],[0,a]],[[],[a,a,a],[0,0,a]]];case 5:return[[[0,a],[a,a],[a]],[[a,a],[0,a,a],[]],[[0,0,a],[0,a,a],[0,a]],[[],[a,
a],[0,a,a]]];case 6:return[[[a],[a,a],[0,a]],[[0,a,a],[a,a],[]],[[0,a],[0,a,a],[0,0,a]],[[],[0,a,a],[a,a]]]}},yd:function(){var b=h.Dc(7),a=this.xd(b,1+h.Dc(9));return{map:a,cols:this.md[b],rows:a[0].length,rotation:0}},e:function(){h.ha.apply(this);this.fa=D.rb.fa();this.f=this.yd();this.size(48*this.f.cols,48*this.f.rows);this.b=-this.width/2;this.a=-this.height/2;this.map=this.f.map[0];this.sc()},yc:function(b){for(var a=this.f.map[this.f.rotation],c=a.length,e;c--;)for(e=0;e<a[c].length;e++)if(a[c][e]&&
b(a[c][e],this.Rc+c,this.ma+e,this))return},va:function(b,a){var c=this,e={},d={};if(!c.Ma)return c.tc(),c.Ma=!0,e[b]=c[b],d[b]=a,c.parent.add(h.va({target:c,aa:!0,duration:3,Y:e,D:d,nb:function(){c.Ma=!1;c.sc()}}))},Ia:function(b){this.y+=b;this.Rc=Math.floor((this.a+this.y)/48)+1},rotate:function(b,a){var c=b||1,e=this.f.rotation+=c;4===e?this.f.rotation=0:-1===e&&(this.f.rotation=3);a&&a(0,0)?(D.qb("rotate"),this.va("rotation",this.rotation+Math.PI/2*b)):this.f.rotation-=c},De:function(b){this.x=
48*b-this.b;this.ma=b+1},left:function(b){b?this.x-=48:this.va("x",this.x-48);this.ma-=1},right:function(b){b?this.x+=48:this.va("x",this.x+48);this.ma+=1}}),F=h.u.extend({x:20,y:140,width:480,height:864,Z:function(){this.stretch(D.m.width-2*this.x,D.m.height-this.y-this.x);this.reset()},Sb:function(){D.m.add(s.Ya.Sb(D.m))},fe:function(b){for(var a=b.length;a--;)if(!b[a])return!1;return!0},Wa:function(b,a){var c=this.map,e=!0;this.f.yc(function(d,f,g){if(c[f+a][g+b])return e=!1});return e},reduce:function(){for(var b=
this.map,a=b.length-1,c=0;a--;)this.fe(b[a])&&(this.ve(b[a],a++),c++);c&&this.pe(c)},xe:function(b){var a=s.Ya.expand(b);a.D.x=b.x-b.width/2;a.D.y=b.y-b.height/2;a.nb=function(){b.remove()};this.add([a,s.Ya.Zd(b)])},ve:function(b,a){var c=1,e=this.map;for(D.qb("line");c<b.length-1;c++)this.xe(b[c]);for(;1<a;a--)for(c=1;10>=c;c++)e[a][c]=e[a-1][c],e[a][c].y+=48;e[0]=[10,0,0,0,0,0,0,0,0,0,0,10]},ne:function(){var b=this,a=this.map,c;D.qb("pop");this.f.yc(function(e,d,f){a[d][f]=c=D.rb.Qa(e+10);b.add(c.L(48*
(f-1),48*(d-1)))});this.f.remove();this.reduce()},reset:function(){var b=19;for(this.map=[];b--;)this.map.push([10,0,0,0,0,0,0,0,0,0,0,10]);this.map.push([10,10,10,10,10,10,10,10,10,10,10,10])},Rd:function(b){b.De(4);b.y=-b.a-48;this.add(this.f=b)}}),G=h.u.extend({fill:"#eee",font:"34px sans-serif",x:240,y:20,width:150,height:60,Z:function(){this.Pa=h.text({text:"0",x:110,y:0});this.S=h.text({text:"1",x:110,y:48});this.add([h.K(z).L(0,10),this.Pa,this.S])},T:function(b){this.Pa.text=parseInt(this.Pa.text,
10)+b;this.R()}}),H=h.u.extend({x:96,y:150,Mb:function(){this.remove();this.da.oa();D.Ke()},Z:function(){var b=h.K(x).L(0,-200),a=h.K(y).L(100,200).set({alpha:0});tween=h.va({target:b,D:{y:0},aa:!0,duration:20});tween2=s.Ya.Yd(a);this.add([b,a,tween,tween2]);D.background.add(h.K(v));D.background.R();this.da=h.o({element:D.m.canvas,Lc:this.Mb.bind(this)});this.da.C.fd.Db=!1}}),I=h.u.extend({y:200,x:120,font:"bold 45px sans-serif",fill:"#eee",stroke:"#000",Mb:function(){this.remove();this.da.oa();D.m.add(new H)},
Z:function(){var b=h.text("Restart").L(120,300);b.t=h.X.ld;this.add([h.K(A),b]);b.Sd("center");this.da=h.o({button:this.Mb.bind(this)})}});h.u.extend({Z:function(){this.add([h.text("CONTROLS"),h.me()])}});
var J=h.u.extend({speed:1.5,S:0,ta:null,mb:null,left:function(b){!this.f.Ma&&this.n.Wa(-1,1)&&this.f.left("touchmove"===b.type)},right:function(b){!this.f.Ma&&this.n.Wa(1,1)&&this.f.right("touchmove"===b.type)},click:function(){this.f.Ma||this.f.rotate(1,this.n.Wa.bind(this.n))},ee:function(){for(var b=1,a=this.n.map[0];10>=b;b++)if(a[b])return!0},be:function(){this.remove();this.rc.remove();this.ta.remove();this.mb.remove();this.da.oa();D.background.R();D.m.add(new I)},Gb:function(){this.f.Ia(this.speed);
!1===this.n.Wa(0,1)&&(this.n.ne(),this.Ac())},Ia:function(){this.f.Ia(24);this.Gb()},Ge:function(){for(D.qb("slide");this.n.Wa(0,1);)this.f.Ia(24);this.n.Sb();this.Gb();this.da.Le(300)},Vb:function(){this.Gb();this.ee()&&this.be()},Pa:function(b){this.S+=b;this.ta.T({1:100,2:250,3:400,4:800}[b]);10<this.S&&(this.speed+=.2,this.S-=10,this.ta.S.text=parseInt(this.ta.S.text,10)+1)},Z:function(){this.n=new F;this.rc=h.rect({x:this.n.x,y:this.n.y,U:this.n.U,V:this.n.V,width:this.n.width,height:this.n.height,
fill:"#000",alpha:.5});this.ta=new G;this.mb=h.clip({x:50,y:30,U:.4,V:.4,width:100,height:100});D.background.add([this.ta,this.mb,this.rc]).R();this.ea=new E;this.add([this.n]).Ac();this.da=h.o({element:D.m.canvas,up:this.click.bind(this),left:this.left.bind(this),right:this.right.bind(this),down:this.Ia.bind(this),buttonB:this.Ge.bind(this)});this.n.pe=this.Pa.bind(this)},Ac:function(){this.f=this.ea.remove();this.n.Rd(this.ea);this.ea=new E;this.ea.L(-this.ea.b,-this.ea.a);this.mb.add(this.ea).R()}}),
D=h.Xd({Ra:{width:480,height:800},Gc:h.clip().add([h.text({fill:"#eee",font:"30px sans-serif",x:10,y:40,update:function(){this.text="Loading: "+(100*q.Qb|0)+"%"}})]),qb:function(b){C[b].currentTime=0;C[b].play()},Ke:function(){this.m.add(new J)},Je:function(){this.rb=h.rb(w).ce(10,2);this.m.add(new H);this.Gc.remove()},Tb:function(){this.background=this.m.he({canvas:h.id("background"),background:!0});this.m.add(this.Gc);this.Sc();q.ready(this.Je.bind(this))}});
