//# sourceMappingURL=all.js.map
(function(b,a){function c(a){b.addEventListener("load",function(){new c.ac(a)})}b.B=c;c.extend=function(a,c){for(var f in c)a[f]=c[f]};c.extend(c,{g:function(a){this.extend(a)},ca:function(a){return function(c){return new a(c)}},id:function(c){return a.getElementById(c)},ready:function(a){b.addEventListener("load",a,!1)},v:function(c){return a.createElement(c)}});c.v.src=function(c,b){var f=a.createElement(c);f.setAttribute("src",b);return f};c.v.K=function(a){return c.v.src("img",a)};c.g.extend=
function(a,b){function f(){}var g,m=this,n=a.e||function(){m.apply(this,arguments)},l;f.prototype=m.prototype;n.prototype=new f;n.extend=c.g.extend;for(g in a)a.hasOwnProperty(g)&&(l=Object.getOwnPropertyDescriptor(a,g),Object.defineProperty(n.prototype,g,l));for(g in b)b.hasOwnProperty(g)&&(l=Object.getOwnPropertyDescriptor(b,g),Object.defineProperty(n,g,l));return n};c.g.prototype.extend=function(a){for(var c in a)this[c]=a[c]}})(this,this.document);
(function(b,a,c){var e=a.v("CANVAS"),d=a.ca;a.extend(a,{ue:function(f){return Math.random()*f},Fc:function(f){return Math.random()*f|0},uf:function(f,a,c){var b=[],e;if(a)for(;a--;)for(b[a]=[],e=0;e<f;e++)b[a][e]=c;else for(;f--;)b.push(c);return b},canvas:function(f,c){var b=a.v("CANVAS");b.setAttribute("width",f);b.setAttribute("height",c);return b},oa:function(f){var c=typeof f;if("object"===c){if(null===f)return"null";if(f instanceof Array)return"array";if(f instanceof a.g)return"j5g3";if(f instanceof
b.HTMLElement||f instanceof b.Image)return"dom";if(f instanceof b.HTMLAudioElement)return"audio"}return c},Ja:function(f,a,c,b){return e.getContext("2d").createLinearGradient(f,a,c,b)},Kf:function(f,a,b,e){e===c&&(e=1);return"rgba("+f+","+a+","+b+","+e+")"},Cf:function(f,a,b,e){e===c&&(e=1);return"hsla("+f+","+a+"%,"+b+"%,"+e+")"}});a.fa={gb:function(){},Yc:function(a){this.O(a);this.t(a);this.end(a)},lf:function(a){this.t(a)},hd:function(){var a=this.Ha;a.clearRect(0,0,this.width,this.height);this.O(a);
this.t(a);this.end(a);this.screen.clearRect(0,0,this.width,this.height);this.screen.drawImage(this.sa,0,0)},jd:function(){var a=this.Ha,c=this.I,b=this.H,e=this.J,d=this.G;0!==b&&0!==d&&(a.clearRect(c,e,b,d),this.O(a),this.t(a),this.end(a),this.screen.clearRect(c,e,b,d),this.screen.drawImage(this.sa,c,e,b,d,c,e,b,d),this.I=this.width,this.J=this.height,this.G=this.H=0)},of:function(){var a=this.Ha;this.clearRect(0,0,this.canvas.width,this.canvas.height);this.O(a);this.t(a);this.end(a)},bf:function(a){a.drawImage(this.source,
this.x+this.b,this.y+this.a)},ab:function(a){a.drawImage(this.rd,0,0,this.width,this.height,this.x+this.b,this.y+this.a,this.width,this.height)}};a.X={Image:function(a){a.drawImage(this.source,this.b,this.a)},eb:function(a){var c=this.source;a.drawImage(c.K,c.x,c.y,c.Vc,c.Dc,this.b,this.a,this.width,this.height)},za:function(a){var c=this.frame,b=c;for(a.translate(this.b,this.a);(b=b.w)!==c;)b.A(a)},Text:function(a){a.fillText(this.text,this.b,this.a)},gd:function(a){for(var c=this.text.split("\n"),
b=0,e=c.length,d=0;b<e;b++)a.fillText(c[b],this.b,this.a+d),d+=this.qa},rf:function(a){a.strokeText(this.text,this.b,this.a)},ld:function(a){a.fillText(this.text,this.b,this.a);a.strokeText(this.text,this.b,this.a)},ga:function(a){var c=this.map,b=c.length,e,d=this.ea,k,q;for(a.translate(this.b,this.a+b*this.ua);b--;)for(e=c[b].length,q=c[b],a.translate(e*this.W,-this.ua);e--;)a.translate(-this.W,0),(k=d[q[e]])&&k.A(a)},df:function(a){var c=this.map,b=0,e,d=c.length,k=this.ea,q;e=(this.W/2|0)+this.offsetX;
var r=(this.ua/2|0)+this.offsetY,t,u;a.translate(this.b,this.a-r);for(t=e;b<d;b++)for(e=c[b].length,q=c[b],t=-t,a.translate(e*this.W-t,r);e--;)a.translate(-this.W,0),(u=k[q[e]])&&u.A(a)}};a.ab={Xc:function(f,c){var b=a.v("CANVAS"),e;b.width=f||this.width;b.height=c||this.height;e=b.getContext("2d",!1);e.translate(-this.x-this.b,-this.y-this.a);this.vc();this.A(e);this.rd=b;this.jc=this.A;this.A=a.fa.ab;return this},Pe:function(a,c){return a(c,e.getContext("2d"))}};a.Aa={gb:function(){return!1},ya:function(a,
c,b){b=b?b.product(this.p,this.x,this.y):this.p.ub(this.x,this.y);b.Vb(a,c);return b.x*b.x+b.y*b.y<=this.d*this.d?this:!1},za:function(a,c,b){var e=this.frame,d=e,k;for(b=b?b.product(this.p,this.x,this.y):this.p.ub(this.x,this.y);(d=d.D)!==e&&!(k=d.Fa(a,c,b)););return k},Rect:function(a,c,b){b=b?b.product(this.p,this.x,this.y):this.p.ub(this.x,this.y);b.Vb(a,c);return 0<b.x&&b.x<this.width&&0<b.y&&b.y<this.height?this:!1},cb:function(a,c,b){var e=this.T,d=this.Kb,k=0,q=e.length;b=b?b.product(this.p,
this.x,this.y):this.p.ub(this.x,this.y);for(b.Vb(a,c);k<q;k+=2)if(a=d[k]*(b.x-e[k])+d[k+1]*(b.y-e[k+1]),0<a)return!1;return this}};a.fd=a.g.extend({j:1,k:0,l:0,m:1,xb:1,Bb:0,Oa:1,Pa:1,e:function(a,b,e,d){a!==c&&(this.j=a,this.k=b,this.l=e,this.m=d)},Be:function(a){this.xb=Math.cos(a);this.Bb=Math.sin(a);return this.jb()},Ce:function(a){this.Oa=a;return this.jb()},De:function(a){this.Pa=a;return this.jb()},scale:function(a,c){this.Oa=a;this.Pa=c;return this.jb()},jb:function(){this.j=this.Oa*this.xb;
this.k=this.Oa*this.Bb;this.l=-this.Pa*this.Bb;this.m=this.Pa*this.xb;return this},ub:function(f,c){return new a.bc(this.j,this.k,this.l,this.m,f||0,c||0)}});a.bc=a.g.extend({j:1,k:0,l:0,m:1,r:0,s:0,e:function(a,b,e,d,l,k){a!==c&&(this.j=a,this.k=b,this.l=e,this.m=d,this.r=l,this.s=k)},translate:function(a,c){this.r+=a;this.s+=c},multiply:function(a,c,b,e,d,k){var q=this.j,r=this.k,t=this.l,u=this.m;this.j=q*a+t*c;this.k=r*a+u*c;this.l=q*b+t*e;this.m=r*b+u*e;this.r+=q*d+t*k;this.s+=r*d+u*k;return this},
clone:function(){return a.ke().multiply(this.j,this.k,this.l,this.m,this.r,this.s)},inverse:function(){var a=this.clone(),c=this.j*this.m-this.k*this.l;a.j=this.m/c;a.k=this.k/-c;a.l=this.l/-c;a.m=this.j/c;a.r=(this.m*this.r-this.l*this.s)/-c;a.s=(this.k*this.r-this.j*this.s)/c;return a},product:function(a,c,b){return this.clone().multiply(a.j,a.k,a.l,a.m,a.r||c||0,a.s||b||0)},reset:function(){this.j=1;this.l=this.k=0;this.m=1;this.s=this.r=0;return this},Qf:function(a,c){this.x=this.j*a+this.l*c+
this.r;this.y=this.k*a+this.m*c+this.s;return this},Vb:function(a,c){var b=this.j*this.m-this.k*this.l;this.x=(this.m*a-this.l*c+this.l*this.s-this.m*this.r)/b;this.y=(-this.k*a+this.j*c+this.k*this.r-this.j*this.s)/b;return this}});a.h=a.g.extend({source:null,w:null,D:null,parent:null,p:null,x:0,y:0,b:0,a:0,width:null,height:null,nc:0,set rotation(a){this.p.Be(this.nc=a)},get rotation(){return this.nc},set U(a){this.p.Ce(a)},get U(){return this.p.Oa},set V(a){this.p.De(a)},get V(){return this.p.Pa},
alpha:1,rc:null,stroke:null,fill:null,font:null,Ma:null,Ib:null,Jb:null,Kc:null,yf:!0,e:function(f){this.p=new a.fd;this.extend(f)},O:function(a){var c=this.p;a.save();1!==this.alpha&&(a.globalAlpha*=this.alpha);null!==this.fill&&(a.fillStyle=this.fill);null!==this.stroke&&(a.strokeStyle=this.stroke);null!==this.font&&(a.font=this.font);null!==this.rc&&(a.globalCompositeOperation=this.rc);null!==this.Ma&&(a.lineWidth=this.Ma);null!==this.Ib&&(a.lineCap=this.Ib);null!==this.Jb&&(a.lineJoin=this.Jb);
null!==this.Kc&&(a.miterLimit=this.Kc);a.transform(c.j,c.k,c.l,c.m,this.x,this.y)},end:function(a){a.restore()},A:a.fa.Yc,yb:null,R:function(){this.parent.R(this)},update:null,remove:function(){this.parent&&(this.D.w=this.w,this.w.D=this.D,this.parent=this.D=null);return this},align:function(a,c){c=c||this.parent;switch(a){case "center":this.x=c.width/2;break;case "left":this.x=0;break;case "right":this.x=c.width-this.width;break;case "middle":this.y=c.height/2;break;case "center middle":this.L(c.width/
2,c.height/2);break;case "origin":this.L(-this.width/2,-this.height/2);break;case "origin top":this.L(-this.width/2,-this.height);break;case "origin bottom":this.L(-this.width/2,0)}return this},L:function(a,c){this.x=a;this.y=c;return this},size:function(a,c){this.width=a;this.height=c;return this},move:function(a,c){this.x+=a;this.y+=c;return this},visible:function(){return 0<this.alpha},stretch:function(a,c){return this.scale(a/this.width,c/this.height)},Of:function(){return a.clip({width:this.width,
height:this.height}).add(this)},tc:a.ab.Xc,vc:function(){this.jc&&(this.A=this.jc)},set:function(a){this.extend(a);return this},Fa:a.Aa.Rect,scale:function(a,c){b.isNaN(a)||(this.U=a);b.isNaN(c)||(this.V=c);return this},rotate:function(a){this.rotation+=a;return this}});a.Image=a.h.extend({e:function(c){switch(a.oa(c)){case "string":c={source:a.id(c)};break;case "dom":c={source:c}}a.h.call(this,c);this.source&&this.Ge(this.source)},t:a.X.Image,zd:function(c){return"string"===typeof c?a.id(c):c},Ge:function(a){this.source=
this.zd(a);null===this.width&&(this.width=this.source.naturalWidth||this.source.width);null===this.height&&(this.height=this.source.naturalHeight||this.source.height)}});a.Text=a.h.extend({text:"",qa:null,sf:null,Sd:function(a){var c=this.Jc();"left"===a?this.b=0:"center"===a?this.b=-c/2:"right"===a&&(this.b=-c);return this},e:function(c){"string"===typeof c&&(c={text:c});a.h.call(this,c);null===this.qa&&this.Jc()},yb:a.X.Text,t:a.X.Text,Hd:function(c,b){var e=(""+c.text).split("\n"),d,l=e.length,
k=0;a:{d=c;do{if(null!==d.font){d=d.font;break a}if(d instanceof a.fb)break}while(d=d.parent);d=void 0}c.O(b);d&&(b.font=d);for(;l--;)d=b.measureText(e[l]),d.width>k&&(k=d.width);null===c.qa&&(c.qa=parseInt(b.font,10));c.end(b);return k},wb:a.h.prototype.O,O:function(a){a.textBaseline="top";this.wb(a)},Jc:function(){return a.ab.Pe(this.Hd,this)}});a.bd=a.h.extend({Ec:"",e:function(c){"string"===typeof c&&(c={Ec:a.v(c).innerHTML});a.h.apply(this,[c])}});a.u=a.h.extend({N:null,ia:0,length:null,Qb:!0,
Je:1,e:function(c){a.h.call(this,c);this.N=[];this.oc();null!==this.Z&&this.Z()},R:function(a){this.parent.R(a||this)},Z:null,update:function(){var a=this.frame,c=a;for(this.Wb&&this.Wb();(c=c.w)!==a;)null!==c.update&&c.update();this.Qb&&((this.ia+=this.Je)>=this.length&&(this.ia=0),this.frame=this.N[this.ia|0])},frame:null,t:a.X.za,stop:function(){this.Qb=!1;return this},play:function(){this.Qb=!0;return this},add:function(c){switch(a.oa(c)){case "function":c=new a.Yb(c);break;case "string":c=new a.Image({source:c});
break;case "array":for(var b=0;b<c.length;b++)this.add(c[b]);return this;case "dom":case "object":c=new a.Image(c);break;case "undefined":case "null":throw"Trying to add undefined object to clip.";}return this.pc(c)},pc:function(a){var c=this.frame;a.parent&&a.remove();c.D.w=a;a.D=c.D;a.w=c;a.parent=this;c.D=a;return this},oc:function(a){var c={};c.D=c.w=c;this.N.push(c);this.go((this.length=this.N.length)-1);return a?this.add(a):this},Ef:function(){return this.frame.w===this.frame},xe:function(a){a=
a===c?this.ia:a;this.N.splice(a,1);this.go(0<a?a-1:0);this.length=this.N.length;return this},go:function(a){this.frame=this.N[this.ia=a];return this},kb:function(a){for(var c=this.N.length,b,e;c--;)for(e=b=this.N[c];(e=e.w)!==b;)a(e);return this},Af:function(a){for(var c=this.frame,b=c,e;(b=e=b.w)!==c;)for(;(e=e.w)!==c;)a(b,e)},tf:function(a){return this.kb(function(c){c.align&&c.align(a)})},Fa:a.Aa.za});a.fb=a.u.extend({canvas:null,Ha:null,screen:null,sa:null,Mf:!1,background:!1,ba:!1,I:0,J:0,H:0,
G:0,Cd:function(){if(!1===this.ba)return this.ba=b.document.body;var c=this.ba=a.v("DIV");c.className="j5g3-stage";b.document.body.appendChild(c);return c},Bd:function(){var c=this.ba||this.Cd();this.canvas||(this.canvas=a.canvas(this.width,this.height),this.background?c.insertBefore(this.canvas,c.firstChild):c.appendChild(this.canvas));this.sa=a.v("CANVAS")},Dd:function(){this.Ha=this.sa.getContext("2d");this.screen=this.canvas.getContext("2d")},e:function(c){a.u.call(this,c);this.Bd();this.ze(this.width||
this.canvas.clientWidth||640,this.height||this.canvas.clientHeight||480);this.Dd()},he:function(c){var b;"string"===typeof c&&(c={canvas:a.id(c)});a.extend(b={width:this.width,height:this.height,ba:this.ba},c);c=new a.fb(b);c.A=a.fa.jd;this.add(c);return c},R:function(a){if(a===c)this.I=this.J=0,this.G=this.height,this.H=this.width;else{var b=a.x+a.b,e=a.y+a.a;b<this.I&&(this.H+=this.I-b,this.I=b);e<this.J&&(this.G+=this.J-e,this.J=e);b+a.width>this.I+this.H&&(this.H=b+a.width-this.I,this.I+this.H>
this.width&&(this.H=this.width-this.I));e+a.height>this.J+this.G&&(this.G=e+a.height-this.J,this.J+this.G>this.height&&(this.G=this.height-this.J))}},ze:function(a,c){if(0===a||0===c)throw Error("Invalid stage resolution: "+a+"x"+c);this.H=this.canvas.width=this.sa.width=a;this.G=this.canvas.height=this.sa.height=c;return this.size(a,c)},A:a.fa.hd});a.Ca=a.h.extend({aa:!1,repeat:Infinity,duration:100,Y:null,target:null,C:null,Va:0,Oc:null,qb:null,e:function(c){c instanceof a.g&&(c={target:c});this.update=
this.start;a.h.apply(this,[c])},A:a.fa.gb,pause:function(){this.kc=this.update;this.update=null;return this},Ae:function(){this.update=this.kc?this.kc:this.start;return this},Rc:function(){this.repeat-=1;this.Za=this.Va=0;return this},Jf:function(){this.Va=0;return this.stop().start()},stop:function(){this.pause().Rc();this.Oc&&this.Oc();return this},Wd:function(a){return a},qc:function(a,c){return this.Y[a]+this.Wd(c)*(this.C[a]-this.Y[a])},Ld:a.h.prototype.remove,remove:function(){this.qb&&this.qb();
this.Ld()},sd:function(){var a=this.target,c;this.duration===this.Va&&(this.Za=1);for(c in this.C)a[c]=this.qc(c,this.Za);this.Va<this.duration?(this.Va++,this.Za+=this.Qe):this.aa?this.remove():this.repeat?this.Rc():this.stop()},start:function(){var a=this.C,c,b=this.target;if(null===this.Y)for(c in this.Y={},a)this.Y[c]=b[c];this.Qe=1/this.duration;this.Za=0;this.update=this.sd;return this},Fa:a.Aa.gb});a.eb=a.h.extend({e:function(c){a.h.call(this,c);if(!this.source)throw Error("Invalid source property for Sprite");
null===this.width&&(this.width=this.source.Vc);null===this.height&&(this.height=this.source.Dc)},t:a.X.eb});a.kd=a.g.extend({width:null,height:null,ib:null,e:function(c){switch(a.oa(c)){case "string":case "dom":case "j5g3":c={source:c}}a.g.call(this,c)},set source(c){switch(a.oa(c)){case "string":case "dom":c=new a.Image(c);break}if(!c)throw Error("Invalid source for Spritesheet.");null===this.width&&c&&(this.width=c.width);null===this.height&&c&&(this.height=c.height);this.Md=c;this.ib=[]},get source(){return this.Md},
select:function(a){var c=[];this.kb(a,function(a){c.push(a)});return c},kb:function(a,c){for(var b=0,e=a.length;b<e;b++)c(this.Sa(a[b]));return this},clip:function(c){var b=a.clip().xe(),e=0,d=0;this.kb(c,function(a){b.oc(a);a.width>e&&(e=a.width);a.height>d&&(d=a.height)});return b.size(e,d).go(0)},push:function(a,c,b,e){this.slice(a,c,b,e);return this},slice:function(a,c,b,e){return this.ib.push({width:b,height:e,source:{K:this.source.source,x:a,y:c,Vc:b,Dc:e}})-1},wf:function(a,c,b,e){return this.Sa(this.slice(a,
c,b,e))},ce:function(a,c,b){b=b||0;var e=2*b,d=this.width/a-e|0,k=this.height/c-e|0,q,r;for(q=0;q<c;q++)for(r=0;r<a;r++)this.slice(r*(d+e)+b,q*(k+e)+b,d,k);return this},Sa:function(c){return new a.eb(this.ib[c])},ea:function(){for(var a=0,c=this.ib.length,b=[];a<c;a++)b.push(this.Sa(a));return b},map:function(c,b){return new a.ga({ea:this.ea(),W:c,ua:b})}});a.ad=a.u.extend({e:function(c){a.u.apply(this,[c])},source:a.u,Ud:function(){this.Gd--?null!==this.fc&&this.fc():this.remove()},ie:10,Mc:null,
count:1,Ie:function(){var a=new this.source;a.Gd=this.ie;a.fc=a.update;a.update=this.Ud;return a},ud:function(){var a=this.Ie();this.pc(a);this.Mc&&this.Mc(a)},Wb:function(){for(var a=this.count;a--;)this.ud()}});a.ga=a.h.extend({ea:null,map:null,W:0,ua:0,offsetX:0,offsetY:0,e:function(c){a.h.apply(this,[c]);null===this.map&&(this.map=[])},Pf:function(a,c){var b=(this.W/2|0)+this.offsetX;return{x:(a*this.W-(c%2?0:-b)|0)-this.b,y:(c*((this.ua/2|0)+this.offsetY)|0)-this.a}},t:a.X.ga});a.Yb=a.g.extend({Ad:a.g,
update:null,A:a.fa.gb,e:function(c){"function"===a.oa(c)&&(c={update:c});this.Ad(c)},remove:a.h.prototype.remove},{rotate:function(a){return function(){a.rotation=6.1>a.rotation?a.rotation+.1:0}}});a.ac=a.g.extend({version:"0.9.0",vb:31,Ab:null,gc:null,mc:0,hc:0,paused:!0,Tc:function(){var a=this;a.wc();a.Ab=function(){a.lc()};a.lc();a.gc=function(){a.wd()};a.hc=b.setInterval(a.gc,a.vb);a.paused=!1;return a},wc:function(){b.clearInterval(this.hc);b.cancelAnimationFrame(this.mc)},na:function(){this.pause();
this.oe&&this.oe()},lc:function(){this.i.A();this.mc=b.requestAnimationFrame(this.Ab)},wd:function(){this.i.update()},Ub:function(){},e:function(d){"function"===typeof d&&(d={Ub:d});d===c&&(d={});e.style.display="none";e.setAttribute("id","j5g3-cache");b.document.body.appendChild(e);a.g.apply(this,[d]);this.Ta||(this.Ta={});this.Ta.canvas||(this.Ta.canvas=a.id("screen"));this.i||(this.i=new a.fb(this.Ta));this.Ub(a,this)},pause:function(){this.wc();this.Ab=function(){};this.paused=!0},Ae:function(){this.paused&&
this.Tc()},set $d(a){this.vb=1E3/a},get $d(){return 1E3/this.vb},Df:function(c,b){var d,n;switch(a.oa(c)){case "string":d=a.id(c);break;case "dom":d=c;break;case "j5g3":d=c.source}return d?(e.width=d.width,e.height=d.height,n=e.getContext("2d"),n.drawImage(d,0,0),n.getImageData(0,0,d.width,d.height)):this.i.Ha.createImageData(c||this.i.canvas.width,b||this.i.canvas.height)}});a.$e=function(){function a(c,b){e["EaseIn"+c]=b;e["EaseOut"+c]=function(a){return 1-b(1-a)};e["EaseInOut"+c]=function(a){return.5>
a?b(2*a)/2:b(-2*a+2)/-2+1}}var c={},b,e={};["Quad","Cubic","Quart","Quint","Expo"].forEach(function(a,b){c[a]=function(a){return Math.pow(a,b+2)}});c.pf=function(a){return 1-Math.cos(a*Math.PI/2)};c.Ye=function(a){return 1-Math.sqrt(1-a*a)};c.af=function(a){return 0===a||1===a?a:-Math.pow(2,8*(a-1))*Math.sin((80*(a-1)-7.5)*Math.PI/15)};c.Ue=function(a){return a*a*(3*a-2)};c.We=function(a){for(var c,b=4;a<((c=Math.pow(2,--b))-1)/11;);return 1/Math.pow(4,3-b)-7.5625*Math.pow((3*c-2)/22-a,2)};for(b in c)a(b,
c[b]);e.gf=function(a){return a};e.qf=function(a){return-Math.cos(a*Math.PI)/2+.5};return e}();a.action=d(a.Yb);a.clip=d(a.u);a.K=d(a.Image);a.Sa=d(a.eb);a.tb=d(a.kd);a.text=d(a.Text);a.i=d(a.fb);a.me=function(){var c=new a.Text("Drag Left/Right/Down to move.\n\nDrag Up to Rotate.\n\nFlick Down to Hard Drop.");c.t=a.X.gd;return c};a.ke=function(){return new a.bc(void 0,void 0,void 0,void 0,void 0,void 0)};a.va=d(a.Ca);a.Bf=d(a.ad);a.map=d(a.ga);a.Ec=d(a.bd);a.Xd=d(a.ac)})(this,this.B);
(function(b,a){a.ed=a.g.extend({$c:{IMG:"load",AUDIO:"canplaythrough",SCRIPT:"load"},$:null,Vd:250,Rb:0,start:null,length:0,Nc:null,rb:null,Ob:null,e:function(c){a.g.apply(this,[c]);this.$={};this.start=new Date},dc:function(){var a,e=0,d=0,f=this;for(a in this.$)d++,this.$.hasOwnProperty(a)&&this.$[a].ready&&e++;this.Rb=e?e/d:0;this.Nc&&this.Nc(this.Rb);d===e?this.Ob&&this.Ob():this.Nd=b.setTimeout(function(){f.dc()},this.Vd)},P:function(c,e){var d=this,f=this.$[e],g;f?f=f.P:(f=a.v(c),this.$[e]=
g={P:f},f.addEventListener(this.$c[c],function(){g.ready=!0;d.rb&&d.rb(g)},!1),f.addEventListener("error",function(){g.ready=!0;b.console.warn("Could not load asset: "+e)},!1),f.setAttribute("src",e),this.length++);return f},pa:function(a){return this.P("IMG",a)},audio:function(c){var b=c.split(".").pop();a.Ua.audio[b]||(c=c.replace(new RegExp("\\."+b+"$"),"."+a.Ua.audio.te));return this.P("AUDIO",c)},data:function(a,e){var d=this,f=new b.XMLHttpRequest,g=this.$[a];g||(g=this.$[a]={source:a,If:f},
f.onreadystatechange=function(){4===f.readyState&&(g.ready=!0,g.ve=f.responseText,e&&e(g),d.rb&&d.rb(f))},f.open("GET",a),f.send());return g},ge:function(a){return this.data(a,function(a){a.ge=JSON.parse(a.ve)})},Lf:function(a){a=this.P("SCRIPT",a);b.document.head.appendChild(a);return a},ready:function(a){a&&(this.Ob=a);this.dc()},na:function(){b.clearTimeout(this.Nd)}});a.je=a.ca(a.ed)})(this,this.B);
(function(b){b.bb=b.g.extend({Wc:null,Zb:null,Lb:0,Mb:0,Pb:0,length:0,Wa:0,Xa:0,0:null,1:null,2:null,3:null,4:null,5:null,6:null,Qc:null});b.bb.ya=b.bb.extend({Qc:function(a,c){var b=a.d+c.d,d=a.x+a.d+a.b,f=a.y+a.d+a.a,g=d-c.d-c.b-c.x,m=f-c.d-c.a-c.y,n=g*g+m*m;if(this.ma=b*b>n)return n=Math.sqrt(n),this.Wc=a,this.Zb=c,this.Lb=g/n,this.Mb=m/n,this.Pb=b-n,this[0]=d-g/2,this[1]=f-m/2,!0}});b.bb.Xb=b.bb.extend({Qc:function(a,c){var b=a.x+a.b,d=c.x+c.b,f=a.y+a.a,g=c.y+c.a,m=b+a.width,n=d+c.width,l=f+a.height,
k=g+c.height,q,r;if(this.ma=!(d>=m||n<=b||g>=l||k<=f))return this.Zb=c,q=this.Wa=n/2-m/2,r=this.Xa=k/2-l/2,this[0]=Math.max(b,d),this[1]=Math.max(f,g),this[2]=Math.min(m,n),this[3]=Math.min(l,k),this[2]-this[0]<this[3]-this[1]?(this.Lb=0>q?-1:1,this.Mb=0,this.Pb=0>q?this[2]-b:m-this[0]):(this.Mb=0>r?-1:1,this.Lb=0,this.Pb=0>r?this[3]-f:l-this[1]),this}});b.$b={ya:function(a){var c=this.d+a.d,b=this.x+this.d+this.b-a.d-a.b-a.x;a=this.y+this.d+this.a-a.d-a.a-a.y;return c*c>b*b+a*a},Xb:function(a){var c=
this.y+this.height,b=a.x+a.width,d=a.y+a.height;return!(a.x>this.x+this.width||b<this.x||a.y>c||d<this.y)},za:function(a){var c=this.frame,b=c,d=!1;for(a={x:a.x-this.x,y:a.y-this.y,width:a.width,height:a.height};(b=b.D)!==c&&!(d=b.ma&&b.ma(a)););return d}};b.h.prototype.ma=b.$b.Xb;b.u.prototype.ma=b.$b.za})(this.B);
(function(b,a){b.M=b.h.extend({shape:null,red:a,green:a,blue:a,xc:"fill",zb:a,ic:a,cc:a,Ma:null,e:function(a){b.h.apply(this,[a])},wb:b.h.prototype.O,O:function(a){if(this.red!==this.zb||this.blue!==this.cc||this.green!==this.ic)this[this.xc]="rgb("+Math.floor(this.red)+","+Math.floor(this.green)+","+Math.floor(this.blue)+")",this.zb=this.zb,this.ic=this.green,this.cc=this.blue;this.wb(a)},sb:function(){},t:function(a){a.beginPath();this.sb(a);a.closePath();a.fill();a.stroke()}});b.ya=b.M.extend({shape:"circle",
d:0,e:function(a){"number"===typeof a&&(a={d:a});b.M.apply(this,[a])},sb:function(a){a.arc(this.d+this.b,this.d+this.a,this.d,0,2*Math.PI,!1)},Fa:b.Aa.ya});b.cd=b.M.extend({Re:0,Se:0,sb:function(a){a.moveTo(this.b,this.a);a.lineTo(this.Re,this.Se)}});b.cb=b.M.extend({shape:"polygon",T:null,Kb:null,e:function(a){b.M.apply(this,[a]);null===this.T&&(this.T=[]);null===this.Kb&&this.Td()},normalize:function(a){var b=Math.sqrt(a[0]*a[0]+a[1]*a[1]);a[0]/=b;a[1]/=b;return a},Td:function(){for(var a=0,b,d=
this.T,f=d.length,g=[],m=[0,0];a<f;a+=2)b=a+2<f?a+2:0,m[0]=d[b]-d[a],m[1]=d[b+1]-d[a+1],this.normalize(m),g.push(m[1],-m[0]);this.Kb=g},sb:function(a){var b=2,d=this.T,f=d.length;for(a.moveTo(d[0],d[1]);b<f;b+=2)a.lineTo(d[b],d[b+1])},Fa:b.Aa.cb},{create:function(a,e){var d=2*Math.PI/a,f=d;for(e.T=[];a--;)e.T.push(Math.cos(f)*e.d,Math.sin(f)*e.d),f+=d;return new b.cb(e)}});b.Rect=b.M.extend({shape:"polygon",e:function(a){b.M.apply(this,[a]);null===this.width&&(this.height=this.width=2*this.d)},t:function(a){a.fillRect(this.b,
this.a,this.width,this.height);a.strokeRect(this.b,this.a,this.width,this.height)}});b.Zc=b.M.extend({shape:"circle",Ib:"round",Jb:"round",xc:"stroke",e:function(a){"number"===typeof a&&(a={Ma:a});b.M.apply(this,[a])},t:function(a){a.strokeRect(0,0,1,1)}});b.Hf=b.ca(b.cb);b.vf=b.ca(b.ya);b.Gf=b.ca(b.cd);b.zf=b.ca(b.Zc);b.rect=b.ca(b.Rect)})(this.B);
(function(b,a){var c=a.v("audio"),e=["wav","mp3","ogg"],d=["audio/wav","audio/mpeg","audio/ogg"];Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}});b.HTMLAudioElement||(b.HTMLAudioElement=b.Te);b.requestAnimationFrame||(b.requestAnimationFrame=b.mozRequestAnimationFrame||b.msRequestAnimationFrame||function(a){return b.setTimeout(a,1E3/60)});b.cancelAnimationFrame||(b.cancelAnimationFrame=b.mozCancelAnimationFrame||b.msCancelAnimationFrame||
function(a){b.clearTimeout(a)});a.Ua={audio:{},Oe:"ontouchstart"in b.document};c&&c.canPlayType&&e.forEach(function(b,e){a.Ua.audio[b]=c.canPlayType(d[e]);a.Ua.audio[b]&&(a.Ua.audio.te=b)})})(this,this.B);(function(b,a){b.o=function(a){return new b.o.dd(a)};b.extend(b.o,{ha:{},dd:b.g.extend({x:0,y:0,yc:0,zc:0,U:1,V:1,F:null,element:null,interval:60,de:null,Ka:null,le:!1,disabled:!1,e:function(c){var e=this;if("string"===typeof c||"object"===typeof c&&c.tagName)c={element:c};b.g.call(this,c);null===this.element?this.element=a.document:"string"===typeof this.element&&(this.element=b.id(this.element));e.F={};e.Ka={};e.Pc=function(){e.Kd()};e.Ga=function(a){e.td(a)};a.addEventListener("resize",this.Ga);
a.addEventListener("scroll",this.Ga);this.de=a.setInterval(this.Pc,this.interval);this.Ga();for(var d in b.o.ha)e.F[d]=new b.o.ha[d](e)},Me:function(c){var b=this;b.disabled=!0;a.setTimeout(function(){b.disabled=!1},c)},pb:function(a,b){if("object"===typeof a)for(var d in a)this.pb(d,a[d]);else{if(!b)throw Error("callback parameter is required.");var f=this.Ka[a];this.Ka[a]=f?function(a){f(a);b(a)}:b}return this},q:function(a,b){if(!this.disabled&&(b.Ff=this,b.name=a,(!this.pe||!1!==this.pe(b))&&
this.Ka[a]))return b.preventDefault(),this.Ka[a](b)},td:function(){var c=this.element;c.getBoundingClientRect?(c=c.getBoundingClientRect(),this.Db=a.scrollX+c.left||0,this.Eb=a.scrollY+c.top||0):(this.Db=c.clientLeft||0,this.Eb=c.clientTop||0)},Kd:function(){if(!1===this.disabled)for(var a in this.F)this.F[a].update()},Sb:function(a,b){a=a*this.U-this.Db;b=b*this.V-this.Eb;this.yc=a-this.x;this.zc=b-this.y;this.x=a;this.y=b},na:function(){this.disable();a.removeEventListener("scroll",this.Ga);a.removeEventListener("resize",
this.Ga);a.clearInterval(this.Pc)},enable:function(){this.disabled=!1;for(var a in this.F)this.F[a].enable()},disable:function(){this.disabled=!0;for(var a in this.F)this.F[a].disable()}}),Ba:b.g.extend({Q:null,P:null,enabled:!1,Ea:null,Da:null,e:function(a){this.Q={};this.c=a;this.P=a.element;this.enable();a.le&&this.Id()},update:function(){},ja:function(a,b){var d=b.bind(this);this.Q[a]=d;this.P.addEventListener(a,d)},ka:function(a){this.P.removeEventListener(a,this.Q[a])},enable:function(){this.enabled||
(this.Ea(),this.enabled=!0);return this},disable:function(){this.enabled&&(this.Da(),this.enabled=!1);return this},na:function(){this.disable();for(var a in this.c.F)if(this.c.F[a]===this){delete this.c.F[a];break}}}),Xe:b.g.extend({e:function(a){b.g.call(this,a)}})})})(this.B,this);
(function(b){b.o.ha.jf=b.o.Ba.extend({wa:1,xa:1,Db:0,Eb:0,uc:!0,hb:function(a){this.c.Sb(a.pageX,a.pageY)},ec:function(a){var c={0:"buttonY",1:"buttonX",2:"buttonA"}[a.button];this.hb(a);this.c.q(c,a);this.c.q("button",a);return!1},Id:function(){this.uc=!1},Jd:function(a){this.uc&&(this.hb(a),(Math.abs(this.c.yc)>this.wa||Math.abs(this.c.zc)>this.xa)&&this.c.q("move",a))},Ea:function(){this.ja("mousemove",this.Jd);this.ja("click",this.ec);this.ja("contextmenu",this.ec)},Da:function(){this.ka("mousemove");
this.ka("click");this.ka("contextmenu")}})})(this.B,this);
(function(b){b.o.ha.Touch=b.o.Ba.extend({wa:35,xa:35,lb:80,Bc:300,Ne:300,touches:null,Lc:"linear",d:25,Cb:0,hb:function(a){this.c.Sb(a.pageX,a.pageY)},Fb:function(a,c){for(var b=a.changedTouches,d=b.length,f,g;d--;)g=b[d].identifier,f=this.touches[g]||(this.touches[g]={id:g}),f.Gb=a,f.Oe=b[g],this.hb(b[d]),c(a,b[d],f,this)},update:function(){var a=this.touches,c;for(c in a)this.c.Sb(a[c].mb,a[c].nb),this.c.q("buttonY",a[c].Gb),this.c.q("button",a[c].Gb)},od:function(a,c,b,d){c=d.c.x;var f=d.c.y,g=
c-b.mb,m=f-b.nb,n=Date.now()-b.Uc,l;g<-d.wa?(b.mb=c,l="left"):g>d.wa&&(b.mb=c,l="right");m<-d.xa?(b.nb=f,l="up"+(l?"_"+l:"")):m>d.xa&&(b.nb=f,l="down"+(l?"_"+l:""));(d.direction=l)&&n>d.Bc&&(d.c.q(l,a),d.c.q("move",a))},pd:function(a,c,b,d){var f=d.c.x,g=d.c.y;c=b.Wa-f;var m=b.Xa-g,f=f-b.re;b=g-b.se;(c>d.wa||c<-d.wa)&&(m>d.xa||m<-d.xa)&&(a.Cb=Math.atan2(b,f),d.c.q("move",a))},Pd:function(a){this.Fb(a,"linear"===this.Lc?this.od:this.pd)},vd:function(a,c){var b=this.c.x-c.Wa,d=this.c.y-c.Xa,f;b<-this.lb?
f="buttonY":b>this.lb&&(f="buttonA");d<-this.lb?f="buttonX":d>this.lb&&(f="buttonB");f?this.c.q(f,a):this.direction&&(this.c.q(this.direction,a),this.c.q("move",a))},Fe:function(a){a.re=a.Wa-Math.cos(this.Cb)*this.d;a.se=a.Xa-Math.sin(this.Cb)*this.d},qd:function(a,c,b,d){b.Uc=Date.now();b.Gb=a;b.Wa=b.mb=d.c.x;b.Xa=b.nb=d.c.y;"radial"===d.Lc&&d.Fe(b)},Qd:function(a){this.direction=!1;this.Fb(a,this.qd)},nd:function(a,c,b,d){c=Date.now()-b.Uc;!d.direction&&c<d.Ne?d.c.q("buttonY",a):c<d.Bc&&d.vd(a,
b);delete d.touches[b.id]},Od:function(a){this.Fb(a,this.nd)},Ea:function(){this.ja("touchmove",this.Pd);this.ja("touchstart",this.Qd);this.ja("touchend",this.Od);this.touches={}},Da:function(){this.ka("touchmove");this.ka("touchstart");this.ka("touchend")}})})(this.B,this);
(function(b,a){var c=a.document,e={32:"buttonB",13:"buttonY",16:"buttonX",17:"buttonA",37:"left",38:"up",39:"right",40:"down",105:"up_right",103:"up_left",99:"down_right",97:"down_left"};b.o.ha.ff=b.o.Ba.extend({La:null,keys:null,Ed:function(a){this.keys[a.keyCode]=a;this.La[a.keyCode]&&a.preventDefault()},e:function(a){this.keys={};b.o.Ba.call(this,a);null===this.La&&b.extend(this.La={},e)},Fd:function(a){this.keys[a.keyCode]=!1},update:function(){var a,b,c;for(c in this.La)if(b=this.keys[c])a=this.La[c],
this.c.q(a,b),32<c&&(b.direction=a,this.c.q("move",b)),this.c.q("button",b)},Ea:function(){this.keys={};this.Q.Gc=this.Ed.bind(this);this.Q.Hc=this.Fd.bind(this);c.addEventListener("keydown",this.Q.Gc);c.addEventListener("keyup",this.Q.Hc)},Da:function(){this.keys={};c.removeEventListener("keydown",this.Q.Gc);c.removeEventListener("keyup",this.Q.Hc)}})})(this.B,this);(function(b,a){a.navigator.Rf&&(b.o.ha.ef=b.o.Ba.extend({Ea:function(){},Da:function(){}}))})(this.B,this);(function(b){b.ae={nf:{xf:b.v.K("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPxJREFUeNqckzEKwjAUhlPB6hm8QUd1EbpVRHAS0eO0N3DuIVx0EaSoHbtoR2/gFVorGv/oSwnRIfHBlwba/Pnf63sO53zDGLuCNdgxs/DAAvQZBCL+iQfIwRL4gGl4IAQpKOlM7IgXUMpBS7nhDs4gARUIwAC0lW+eYCLVU24fwi1rkNqe2cfhvSr5FRa3V7JOapGOFgKZPNf4smQWidyoAq6FQPVLYGQhENQ7ysWnwphGQYWvHcxA08KBaKi5mkLwRx8MxSJaeYznVqtHCTL6My7Vp6e5vIGuyD+mvEpq6VDmp+HToOU0eCIih8b5BFbgYmhfuJ6CzkuAAQBw8IUZ2uqgnAAAAABJRU5ErkJggg=="),
Nf:b.v.K("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAO5JREFUeNpi/P//PwMeEA3EL4B4Ly4FjAQM2APEH4E4GKcKkAE4sD0Q/wXi30BshEsdEx7b04AYJM8CxDmkukANiL/+R4DPQKyCTS0oDJKA5kgBsTgSlodiZPAIiB8C8WsgfgnEr4D4KcgUbyB+/Z908AKInWBOMQXiOyRovgXE+uAYRPKPIhCfIULzKSCWg+lDDxRhIL6LR/NDIBbEF42fgVgIT9SKgiIOWQDdAEsgFsBjACcQW+AzwADNNZ1A3AjE75DEDfElpPnQ5Lscmphg4rJAPAeIfwHxKmQ96AYsBGJnPPkDFN0LkMUAAgwAJMvR40MRRPUAAAAASUVORK5CYII=")},mf:{Ze:function(){}},
Ve:{cf:function(){}},Text:{kf:function(a){var b=this.stroke||this.fill||a.fillStyle,e=this.Ma||a.lineWidth;a.strokeStyle=b;a.globalAlpha=.2;a.lineWidth=e+10;a.strokeText(this.text,this.b,this.a);a.globalAlpha=.4;a.lineWidth=e+5;a.strokeText(this.text,this.b,this.a);a.globalAlpha=1;a.lineWidth=e;a.strokeText(this.text,this.b,this.a);a.globalCompositeOperation="lighter";a.fillStyle=b;a.fillText(this.text,this.b,this.a)},hf:function(a){this.yb(a);a.scale(1,-1);var b=this.a;this.a-=2*this.qa;this.Ja||
(this.Ja=a.createLinearGradient(-this.b,this.a,-this.b,this.a+this.qa),this.Ja.addColorStop(1,this.fill||a.fillStyle),this.Ja.addColorStop(0,"transparent"));a.fillStyle=this.Ja;this.yb(a);this.a=b}},$a:{Yd:function(a){return new b.Ca({target:a,duration:30,aa:!0,Y:{alpha:0},C:{alpha:1}})},Zd:function(a){return new b.Ca({target:a,aa:!0,duration:30,C:{alpha:0}})},expand:function(a,c){c=c||1.5;return new b.Ca({target:a,aa:!0,duration:30,C:{U:a.U+c,V:a.V+c}})},Tb:function(a){a=new b.Ca({target:a,d:3,duration:10,
aa:!0,C:{x:a.x,y:a.y}});a.qc=function(a,e){return 1===e?this.C[a]:this.Y[a]-this.d+b.ue(2*this.d)};return a}}}})(this.B);var h=window.B,p=h.je(),s=h.ae,v=p.pa("resources/background.jpg"),w=p.pa("resources/blocks-ss.png"),x=p.pa("resources/logo.png"),y=p.pa("resources/play.png"),z=p.pa("resources/score.png"),A=p.pa("resources/gameover.png"),C={pop:p.audio("resources/pop.ogg"),slide:p.audio("resources/slide.ogg"),rotate:p.audio("resources/rotate.ogg"),line:p.audio("resources/line.ogg"),gameover:p.audio("resources/gameover.mp3")},E=h.ga.extend({md:[3,4,3,2,3,3,3],W:48,ua:48,Sc:1,la:0,xd:function(b,a){switch(b){case 0:return[[[a],
[a],[a,a]],[[a,a,a],[a]],[[0,a,a],[0,0,a],[0,0,a]],[[],[0,0,a],[a,a,a]]];case 1:return[[[0,a],[0,a],[0,a],[0,a]],[[],[a,a,a,a],[],[]],[[0,0,a],[0,0,a],[0,0,a],[0,0,a]],[[],[],[a,a,a,a],[]]];case 2:return[[[a],[a,a],[a]],[[a,a,a],[0,a],[]],[[0,0,a],[0,a,a],[0,0,a]],[[],[0,a],[a,a,a]]];case 3:return[[[a,a],[a,a]],[[a,a],[a,a]],[[a,a],[a,a]],[[a,a],[a,a]]];case 4:return[[[0,a],[0,a],[a,a]],[[a],[a,a,a],[]],[[0,a,a],[0,a],[0,a]],[[],[a,a,a],[0,0,a]]];case 5:return[[[0,a],[a,a],[a]],[[a,a],[0,a,a],[]],
[[0,0,a],[0,a,a],[0,a]],[[],[a,a],[0,a,a]]];case 6:return[[[a],[a,a],[0,a]],[[0,a,a],[a,a],[]],[[0,a],[0,a,a],[0,0,a]],[[],[0,a,a],[a,a]]]}},yd:function(){var b=h.Fc(7),a=this.xd(b,1+h.Fc(9));return{map:a,cols:this.md[b],rows:a[0].length,rotation:0}},e:function(){h.ga.apply(this);this.ea=D.tb.ea();this.f=this.yd();this.size(48*this.f.cols,48*this.f.rows);this.b=-this.width/2;this.a=-this.height/2;this.map=this.f.map[0];this.tc()},Ac:function(b){for(var a=this.f.map[this.f.rotation],c=a.length,e;c--;)for(e=
0;e<a[c].length;e++)if(a[c][e]&&b(a[c][e],this.Sc+c,this.la+e,this))return},va:function(b,a){var c=this,e={},d={};if(!c.Na)return c.vc(),c.Na=!0,e[b]=c[b],d[b]=a,c.parent.add(h.va({target:c,aa:!0,duration:3,Y:e,C:d,qb:function(){c.Na=!1;c.tc()}}))},Ia:function(b){this.y+=b;this.Sc=Math.floor((this.a+this.y)/48)+1},rotate:function(b,a){var c=b||1,e=this.f.rotation+=c;4===e?this.f.rotation=0:-1===e&&(this.f.rotation=3);a&&a(0,0)?(D.Ra("rotate"),this.va("rotation",this.rotation+Math.PI/2*b)):this.f.rotation-=
c},Ee:function(b){this.x=48*b-this.b;this.la=b+1},left:function(b){b?this.x-=48:this.va("x",this.x-48);this.la-=1},right:function(b){b?this.x+=48:this.va("x",this.x+48);this.la+=1}}),F=h.u.extend({x:20,y:140,width:480,height:864,Z:function(){this.stretch(D.i.width-2*this.x,D.i.height-this.y-this.x);this.reset()},Tb:function(){D.i.add(s.$a.Tb(D.i))},fe:function(b){for(var a=b.length;a--;)if(!b[a])return!1;return!0},Ya:function(b,a){var c=this.map,e=!0;this.f.Ac(function(d,f,g){if(c[f+a][g+b])return e=
!1});return e},reduce:function(){for(var b=this.map,a=b.length-1,c=0;a--;)this.fe(b[a])&&(this.we(b[a],a++),c++);c&&this.qe(c)},ye:function(b){var a=s.$a.expand(b);a.C.x=b.x-b.width/2;a.C.y=b.y-b.height/2;a.qb=function(){b.remove()};this.add([a,s.$a.Zd(b)])},we:function(b,a){var c=1,e=this.map;for(D.Ra("line");c<b.length-1;c++)this.ye(b[c]);for(;1<a;a--)for(c=1;10>=c;c++)e[a][c]=e[a-1][c],e[a][c].y+=48;e[0]=[10,0,0,0,0,0,0,0,0,0,0,10]},ne:function(){var b=this,a=this.map,c;D.Ra("pop");this.f.Ac(function(e,
d,f){a[d][f]=c=D.tb.Sa(e+10);b.add(c.L(48*(f-1),48*(d-1)))});this.f.remove();this.reduce()},reset:function(){var b=19;for(this.map=[];b--;)this.map.push([10,0,0,0,0,0,0,0,0,0,0,10]);this.map.push([10,10,10,10,10,10,10,10,10,10,10,10])},Rd:function(b){b.Ee(4);b.y=-b.a-48;this.add(this.f=b)}}),G=h.u.extend({fill:"#eee",font:"34px sans-serif",x:240,y:20,width:150,height:60,Z:function(){this.Qa=h.text({text:"0",x:110,y:0});this.S=h.text({text:"1",x:110,y:48});this.add([h.K(z).L(0,10),this.Qa,this.S])},
T:function(b){this.Qa.text=parseInt(this.Qa.text,10)+b;this.R()}}),H=h.u.extend({x:96,y:150,Nb:function(){this.remove();this.ra.na();D.Le()},Z:function(){var b=h.K(x).L(0,-200),a=h.K(y).L(100,200).set({alpha:0});tween=h.va({target:b,C:{y:0},aa:!0,duration:20});tween2=s.$a.Yd(a);this.add([b,a,tween,tween2]);D.background.add(h.K(v));D.background.R();this.ra=h.o(D.i.canvas).pb("button",this.Nb.bind(this))}}),I=h.u.extend({y:200,x:120,font:"bold 45px sans-serif",fill:"#eee",stroke:"#000",Nb:function(){this.remove();
this.ra.na();D.i.add(new H)},Z:function(){var b=h.text("Restart").L(120,300);b.t=h.X.ld;this.add([h.K(A),b]);b.Sd("center");this.ra=h.o(D.i.canvas).pb("button",this.Nb.bind(this))}});h.u.extend({Z:function(){this.add([h.text("CONTROLS"),h.me()])}});
var J=h.u.extend({speed:1.5,S:0,ta:null,ob:null,left:function(b){!this.f.Na&&this.n.Ya(-1,1)&&this.f.left("touchmove"===b.type)},right:function(b){!this.f.Na&&this.n.Ya(1,1)&&this.f.right("touchmove"===b.type)},click:function(){this.f.Na||this.f.rotate(1,this.n.Ya.bind(this.n))},ee:function(){for(var b=1,a=this.n.map[0];10>=b;b++)if(a[b])return!0},be:function(){this.remove();this.sc.remove();this.ta.remove();this.ob.remove();this.ra.na();D.Ra("gameover");D.background.R();D.i.add(new I)},Hb:function(){this.f.Ia(this.speed);
!1===this.n.Ya(0,1)&&(this.n.ne(),this.Cc())},Ia:function(){this.f.Ia(24);this.Hb()},He:function(){for(D.Ra("slide");this.n.Ya(0,1);)this.f.Ia(24);this.n.Tb();this.Hb();this.ra.Me(300)},Wb:function(){this.Hb();this.ee()&&this.be()},Qa:function(b){this.S+=b;this.ta.T({1:100,2:250,3:400,4:800}[b]);10<this.S&&(this.speed+=.2,this.S-=10,this.ta.S.text=parseInt(this.ta.S.text,10)+1)},Z:function(){this.n=new F;this.sc=h.rect({x:this.n.x,y:this.n.y,U:this.n.U,V:this.n.V,width:this.n.width,height:this.n.height,
fill:"#000",alpha:.5});this.ta=new G;this.ob=h.clip({x:50,y:30,U:.4,V:.4,width:100,height:100});D.background.add([this.ta,this.ob,this.sc]).R();this.da=new E;this.add([this.n]).Cc();this.ra=h.o(D.i.canvas).pb({up:this.click.bind(this),left:this.left.bind(this),right:this.right.bind(this),down:this.Ia.bind(this),buttonB:this.He.bind(this)});this.n.qe=this.Qa.bind(this)},Cc:function(){this.f=this.da.remove();this.n.Rd(this.da);this.da=new E;this.da.L(-this.da.b,-this.da.a);this.ob.add(this.da).R()}}),
D=h.Xd({Ta:{width:480,height:800},Ic:h.clip().add([h.text({fill:"#eee",font:"30px sans-serif",x:10,y:40,update:function(){this.text="Loading: "+(100*p.Rb|0)+"%"}})]),Ra:function(b){C[b].currentTime=0;C[b].play()},Le:function(){this.i.add(new J)},Ke:function(){this.tb=h.tb(w).ce(10,2);this.i.add(new H);this.Ic.remove()},Ub:function(){this.background=this.i.he({canvas:h.id("background"),background:!0});this.i.add(this.Ic);this.Tc();p.ready(this.Ke.bind(this))}});
