(function(d,b,e){function c(b){d.addEventListener("load",function(){new c.Engine(b)})}d.j5g3=c;c.extend=function(c,a){for(var f in a)c[f]=a[f]};c.extend(c,{Class:function(c){this.extend(c)},factory:function(c){return function(a){return new c(a)}},id:function(c){return b.getElementById(c)},ready:function(c){d.addEventListener("load",c,!1)},dom:function(c){return b.createElement(c)}});c.dom.src=function(c,a){var f=b.createElement(c);f.setAttribute("src",a);return f};c.dom.image=function(b){return c.dom.src("img",
b)};c.Class.extend=function(b,a){var f,h=this,e=b.init||function(){h.apply(this,arguments)},d=function(){};d.prototype=h.prototype;e.prototype=new d;e.extend=c.Class.extend;for(f in b)b.hasOwnProperty(f)&&(d=Object.getOwnPropertyDescriptor(b,f),Object.defineProperty(e.prototype,f,d));for(f in a)a.hasOwnProperty(f)&&(d=Object.getOwnPropertyDescriptor(a,f),Object.defineProperty(e,f,d));return e};c.Class.prototype.extend=function(c){for(var a in c)this[a]=c[a]}})(this,this.document);
(function(d,b,e){var c=b.dom("CANVAS"),g=b.factory;b.extend(b,{rand:function(a){return Math.random()*a},irand:function(a){return Math.random()*a|0},ary:function(a,f,c){var b=[],e;if(f)for(;f--;)for(b[f]=[],e=0;e<a;e++)b[f][e]=c;else for(;a--;)b.push(c);return b},canvas:function(a,f){var c=b.dom("CANVAS");c.setAttribute("width",a);c.setAttribute("height",f);return c},get_type:function(a){var f=typeof a;if("object"===f){if(null===a)return"null";if(a instanceof Array)return"array";if(a instanceof b.Class)return"j5g3";
if(a instanceof d.HTMLElement||a instanceof d.Image)return"dom";if(a instanceof d.HTMLAudioElement)return"audio"}return f},gradient:function(a,f,h,b){return c.getContext("2d").createLinearGradient(a,f,h,b)},rgba:function(a,f,c,b){b===e&&(b=1);return"rgba("+a+","+f+","+c+","+b+")"},hsla:function(a,f,c,b){b===e&&(b=1);return"hsla("+a+","+f+"%,"+c+"%,"+b+")"}});b.Draw={Void:function(){},Default:function(a){this.begin(a);this.paint(a);this.end(a)},NoTransform:function(a){this.paint(a)},Root:function(){var a=
this.context;a.clearRect(0,0,this.width,this.height);this.begin(a);this.paint(a);this.end(a);this.screen.clearRect(0,0,this.width,this.height);this.screen.drawImage(this.renderCanvas,0,0)},RootDirty:function(){var a=this.context,f=this._dx,c=this._dw,b=this._dy,e=this._dh;0!==c&&0!==e&&(a.clearRect(f,b,c,e),this.begin(a),this.paint(a),this.end(a),this.screen.clearRect(f,b,c,e),this.screen.drawImage(this.renderCanvas,f,b,c,e,f,b,c,e),this._dx=this._dy=null,this._dh=this._dw=0)},RootDirect:function(){var a=
this.context;this.clearRect(0,0,this.canvas.width,this.canvas.height);this.begin(a);this.paint(a);this.end(a)},FastImage:function(a){a.drawImage(this.source,this.x+this.cx,this.y+this.cy)},Cache:function(a){a.drawImage(this._cache_source,0,0,this.width,this.height,this.x+this.cx,this.y+this.cy,this.width,this.height)}};b.Paint={Image:function(a){a.drawImage(this.source,this.cx,this.cy)},Sprite:function(a){var f=this.source;a.drawImage(f.image,f.x,f.y,f.w,f.h,this.cx,this.cy,this.width,this.height)},
Container:function(a){var f=this.frame,c=f;for(a.translate(this.cx,this.cy);(c=c._next)!==f;)c.draw(a)},Text:function(a){a.fillText(this.text,this.cx,this.cy)},MultilineText:function(a){for(var f=this.text.split("\n"),c=0,b=f.length,e=0;c<b;c++)a.fillText(f[c],this.cx,this.cy+e),e+=this.line_height},TextStroke:function(a){a.strokeText(this.text,this.cx,this.cy)},TextStrokeFill:function(a){a.fillText(this.text,this.cx,this.cy);a.strokeText(this.text,this.cx,this.cy)},Map:function(a){var f=this.map,
c=f.length,b,e=this.sprites,g,d;for(a.translate(this.cx,this.cy+c*this.th);c--;)for(b=f[c].length,d=f[c],a.translate(b*this.tw,-this.th);b--;)a.translate(-this.tw,0),(g=e[d[b]])&&g.draw(a)},Isometric:function(a){var f=this.map,c=0,b,e=f.length,g=this.sprites,d;b=(this.tw/2|0)+this.offsetX;var n=(this.th/2|0)+this.offsetY,q,r;a.translate(this.cx,this.cy-n);for(q=b;c<e;c++)for(b=f[c].length,d=f[c],q=-q,a.translate(b*this.tw-q,n);b--;)a.translate(-this.tw,0),(r=g[d[b]])&&r.draw(a)}};b.Cache={Canvas:function(a,
f){var c=b.dom("CANVAS"),e;c.width=a||this.width;c.height=f||this.height;e=c.getContext("2d",!1);e.translate(-this.x-this.cx,-this.y-this.cy);this.clear_cache();this.draw(e);this._cache_source=c;this._oldPaint=this.draw;this.draw=b.Draw.Cache;return this},use:function(a,f){return a(f,c.getContext("2d"))}};b.HitTest={Void:function(){return!1},Circle:function(a,f,c){c=c?c.product(this.M,this.x,this.y):this.M.to_m(this.x,this.y);c.to_client(a,f);return c.x*c.x+c.y*c.y<=this.radius*this.radius?this:!1},
Container:function(a,f,c){var b=this.frame,e=b,g;for(c=c?c.product(this.M,this.x,this.y):this.M.to_m(this.x,this.y);(e=e._previous)!==b&&!(g=e.at(a,f,c)););return g},Rect:function(a,f,c){c=c?c.product(this.M,this.x,this.y):this.M.to_m(this.x,this.y);c.to_client(a,f);return 0<c.x&&c.x<this.width&&0<c.y&&c.y<this.height?this:!1},Polygon:function(a,c,b){var e=this.points,g=this.normals,d=0,k=e.length;b=b?b.product(this.M,this.x,this.y):this.M.to_m(this.x,this.y);for(b.to_client(a,c);d<k;d+=2)if(a=g[d]*
(b.x-e[d])+g[d+1]*(b.y-e[d+1]),0<a)return!1;return this}};b.MatrixLite=b.Class.extend({a:1,b:0,c:0,d:1,_cos:1,_sin:0,scaleX:1,scaleY:1,init:function(a,c,b,d){a!==e&&(this.a=a,this.b=c,this.c=b,this.d=d)},setRotation:function(a){this._cos=Math.cos(a);this._sin=Math.sin(a);return this.calc4()},setScaleX:function(a){this.scaleX=a;return this.calc4()},setScaleY:function(a){this.scaleY=a;return this.calc4()},scale:function(a,c){this.scaleX=a;this.scaleY=c;return this.calc4()},calc4:function(){this.a=this.scaleX*
this._cos;this.b=this.scaleX*this._sin;this.c=-this.scaleY*this._sin;this.d=this.scaleY*this._cos;return this},to_m:function(a,c){return new b.Matrix(this.a,this.b,this.c,this.d,a||0,c||0)}});b.Matrix=b.Class.extend({a:1,b:0,c:0,d:1,e:0,f:0,init:function(a,c,b,d,g,p){a!==e&&(this.a=a,this.b=c,this.c=b,this.d=d,this.e=g,this.f=p)},translate:function(a,c){this.e+=a;this.f+=c},multiply:function(a,c,b,e,d,g){var k=this.a,n=this.b,q=this.c,r=this.d;this.a=k*a+q*c;this.b=n*a+r*c;this.c=k*b+q*e;this.d=n*
b+r*e;this.e+=k*d+q*g;this.f+=n*d+r*g;return this},clone:function(){return b.matrix().multiply(this.a,this.b,this.c,this.d,this.e,this.f)},inverse:function(){var a=this.clone(),c=this.a*this.d-this.b*this.c;a.a=this.d/c;a.b=this.b/-c;a.c=this.c/-c;a.d=this.a/c;a.e=(this.d*this.e-this.c*this.f)/-c;a.f=(this.b*this.e-this.a*this.f)/c;return a},product:function(a,c,b){return this.clone().multiply(a.a,a.b,a.c,a.d,a.e||c||0,a.f||b||0)},reset:function(){this.a=1;this.c=this.b=0;this.d=1;this.f=this.e=0;
return this},to_world:function(a,c){this.x=this.a*a+this.c*c+this.e;this.y=this.b*a+this.d*c+this.f;return this},to_client:function(a,c){var b=this.a*this.d-this.b*this.c;this.x=(this.d*a-this.c*c+this.c*this.f-this.d*this.e)/b;this.y=(-this.b*a+this.a*c+this.b*this.e-this.a*this.f)/b;return this}});b.DisplayObject=b.Class.extend({source:null,_next:null,_previous:null,parent:null,M:null,x:0,y:0,cx:0,cy:0,width:null,height:null,_rotation:0,set rotation(a){this.M.setRotation(this._rotation=a)},get rotation(){return this._rotation},
set sx(a){this.M.setScaleX(a)},get sx(){return this.M.scaleX},set sy(a){this.M.setScaleY(a)},get sy(){return this.M.scaleY},alpha:1,blending:null,stroke:null,fill:null,font:null,line_width:null,line_cap:null,line_join:null,miter_limit:null,dirty:!0,init:function(a){this.M=new b.MatrixLite;this.extend(a)},begin:function(a){var c=this.M;a.save();1!==this.alpha&&(a.globalAlpha*=this.alpha);null!==this.fill&&(a.fillStyle=this.fill);null!==this.stroke&&(a.strokeStyle=this.stroke);null!==this.font&&(a.font=
this.font);null!==this.blending&&(a.globalCompositeOperation=this.blending);null!==this.line_width&&(a.lineWidth=this.line_width);null!==this.line_cap&&(a.lineCap=this.line_cap);null!==this.line_join&&(a.lineJoin=this.line_join);null!==this.miter_limit&&(a.miterLimit=this.miter_limit);a.transform(c.a,c.b,c.c,c.d,this.x,this.y)},end:function(a){a.restore()},draw:b.Draw.Default,_paint:null,invalidate:function(){this.parent.invalidate(this)},update:null,remove:function(){this.parent&&(this._previous._next=
this._next,this._next._previous=this._previous,this.parent=this._previous=null);return this},align:function(a,c){c=c||this.parent;switch(a){case "center":this.x=c.width/2;break;case "left":this.x=0;break;case "right":this.x=c.width-this.width;break;case "middle":this.y=c.height/2;break;case "center middle":this.pos(c.width/2,c.height/2);break;case "origin":this.pos(-this.width/2,-this.height/2);break;case "origin top":this.pos(-this.width/2,-this.height);break;case "origin bottom":this.pos(-this.width/
2,0)}return this},pos:function(a,c){this.x=a;this.y=c;return this},size:function(a,c){this.width=a;this.height=c;return this},move:function(a,c){this.x+=a;this.y+=c;return this},visible:function(){return 0<this.alpha},stretch:function(a,c){return this.scale(a/this.width,c/this.height)},to_clip:function(){return b.clip({width:this.width,height:this.height}).add(this)},cache:b.Cache.Canvas,clear_cache:function(){this._oldPaint&&(this.draw=this._oldPaint)},set:function(a){this.extend(a);return this},
at:b.HitTest.Rect,scale:function(a,c){d.isNaN(a)||(this.sx=a);d.isNaN(c)||(this.sy=c);return this},rotate:function(a){this.rotation+=a;return this}});b.Image=b.DisplayObject.extend({init:function(a){switch(b.get_type(a)){case "string":a={source:b.id(a)};break;case "dom":a={source:a}}b.DisplayObject.call(this,a);this.source&&this.set_source(this.source)},paint:b.Paint.Image,_get_source:function(a){return"string"===typeof a?b.id(a):a},set_source:function(a){this.source=this._get_source(a);null===this.width&&
(this.width=this.source.naturalWidth||this.source.width);null===this.height&&(this.height=this.source.naturalHeight||this.source.height)}});b.Text=b.DisplayObject.extend({text:"",line_height:null,_align:null,align_text:function(a){var c=this.measure();"left"===a?this.cx=0:"center"===a?this.cx=-c/2:"right"===a&&(this.cx=-c);return this},init:function(a){"string"===typeof a&&(a={text:a});b.DisplayObject.call(this,a);null===this.line_height&&this.measure()},_paint:b.Paint.Text,paint:b.Paint.Text,_measure:function(a,
c){var e=(""+a.text).split("\n"),d,g=e.length,p=0;a:{d=a;do{if(null!==d.font){d=d.font;break a}if(d instanceof b.Stage)break}while(d=d.parent);d=void 0}a.begin(c);d&&(c.font=d);for(;g--;)d=c.measureText(e[g]),d.width>p&&(p=d.width);null===a.line_height&&(a.line_height=parseInt(c.font,10));a.end(c);return p},_begin:b.DisplayObject.prototype.begin,begin:function(a){a.textBaseline="top";this._begin(a)},measure:function(){return b.Cache.use(this._measure,this)}});b.Html=b.DisplayObject.extend({html:"",
init:function(a){"string"===typeof a&&(a={html:b.dom(a).innerHTML});b.DisplayObject.apply(this,[a])}});b.Clip=b.DisplayObject.extend({_frames:null,_frame:0,length:null,playing:!0,st:1,init:function(a){b.DisplayObject.call(this,a);this._frames=[];this.add_frame();null!==this.setup&&this.setup()},invalidate:function(a){this.parent.invalidate(a||this)},setup:null,update:function(){var a=this.frame,c=a;for(this.update_frame&&this.update_frame();(c=c._next)!==a;)null!==c.update&&c.update();this.playing&&
((this._frame+=this.st)>=this.length&&(this._frame=0),this.frame=this._frames[this._frame|0])},frame:null,paint:b.Paint.Container,stop:function(){this.playing=!1;return this},play:function(){this.playing=!0;return this},add:function(a){switch(b.get_type(a)){case "function":a=new b.Action(a);break;case "string":a=new b.Image({source:a});break;case "array":for(var c=0;c<a.length;c++)this.add(a[c]);return this;case "dom":case "object":a=new b.Image(a);break;case "undefined":case "null":throw"Trying to add undefined object to clip.";
}return this.add_object(a)},add_object:function(a){var c=this.frame;a.parent&&a.remove();c._previous._next=a;a._previous=c._previous;a._next=c;a.parent=this;c._previous=a;return this},add_frame:function(a){var c={};c._previous=c._next=c;this._frames.push(c);this.go((this.length=this._frames.length)-1);return a?this.add(a):this},is_frame_empty:function(){return this.frame._next===this.frame},remove_frame:function(a){a=a===e?this._frame:a;this._frames.splice(a,1);this.go(0<a?a-1:0);this.length=this._frames.length;
return this},go:function(a){this.frame=this._frames[this._frame=a];return this},each:function(a){for(var c=this._frames.length,b,e;c--;)for(e=b=this._frames[c];(e=e._next)!==b;)a(e);return this},each_pair:function(a){for(var c=this.frame,b=c,e;(b=e=b._next)!==c;)for(;(e=e._next)!==c;)a(b,e)},align_children:function(a){return this.each(function(c){c.align&&c.align(a)})},at:b.HitTest.Container});b.Stage=b.Clip.extend({canvas:null,context:null,screen:null,renderCanvas:null,smoothing:!1,background:!1,
container:!1,_dx:0,_dy:0,_dw:0,_dh:0,_init_container:function(){if(!1===this.container)return this.container=d.document.body;if("dom"===b.get_type(this.container))return this.container;var a=this.container=b.dom("DIV");a.className="j5g3-stage";d.document.body.appendChild(a);return a},_init_canvas:function(){var a=this._init_container();this.canvas||(this.canvas=b.canvas(this.width,this.height),this.background?a.insertBefore(this.canvas,a.firstChild):a.appendChild(this.canvas));this.renderCanvas=b.dom("CANVAS")},
_init_context:function(){this.context=this.renderCanvas.getContext("2d");this.screen=this.canvas.getContext("2d")},init:function(a){b.Clip.call(this,a);this._init_canvas();this.resolution(this.width||this.canvas.clientWidth||640,this.height||this.canvas.clientHeight||480);this._init_context()},layer:function(a){var c;"string"===typeof a&&(a={canvas:b.id(a)});b.extend(c={width:this.width,height:this.height,container:this.container},a);a=new b.Stage(c);a.draw=b.Draw.RootDirty;this.add(a);return a},
invalidate:function(a){if(a===e)this._dx=this._dy=0,this._dh=this.height,this._dw=this.width;else{var c=a.x+a.cx,b=a.y+a.cy;null===this._dx?this._dx=c:c<this._dx&&(this._dw+=this._dx-c,this._dx=c);null===this._dy&&(this._dy=b);b<this._dy&&(this._dh+=this._dy-b,this._dy=b);c+a.width>this._dx+this._dw&&(this._dw=c+a.width-this._dx,this._dx+this._dw>this.width&&(this._dw=this.width-this._dx));b+a.height>this._dy+this._dh&&(this._dh=b+a.height-this._dy,this._dy+this._dh>this.height&&(this._dh=this.height-
this._dy))}},resolution:function(a,c){if(0===a||0===c)throw Error("Invalid stage resolution: "+a+"x"+c);this._dw=this.canvas.width=this.renderCanvas.width=a;this._dh=this.canvas.height=this.renderCanvas.height=c;return this.size(a,c)},draw:b.Draw.Root});b.Tween=b.DisplayObject.extend({auto_remove:!1,repeat:Infinity,duration:100,from:null,target:null,to:null,t:0,on_stop:null,on_remove:null,init:function(a){a instanceof b.Class&&(a={target:a});this.update=this.start;b.DisplayObject.apply(this,[a])},
draw:b.Draw.Void,pause:function(){this._olddraw=this.update;this.update=null;return this},resume:function(){this.update=this._olddraw?this._olddraw:this.start;return this},rewind:function(){this.repeat-=1;this.vf=this.t=0;return this},restart:function(){this.t=0;return this.stop().start()},stop:function(){this.pause().rewind();if(this.on_stop)this.on_stop();return this},easing:function(a){return a},apply_tween:function(a,c){return this.from[a]+this.easing(c)*(this.to[a]-this.from[a])},_remove:b.DisplayObject.prototype.remove,
remove:function(){if(this.on_remove)this.on_remove();this._remove()},_calculate:function(){var a=this.target,c;this.duration===this.t&&(this.vf=1);for(c in this.to)a[c]=this.apply_tween(c,this.vf);this.t<this.duration?(this.t++,this.vf+=this.v):this.auto_remove?this.remove():this.repeat?this.rewind():this.stop()},start:function(){var a=this.to,c,b=this.target;if(null===this.from)for(c in this.from={},a)this.from[c]=b[c];this.v=1/this.duration;this.vf=0;this.update=this._calculate;return this},at:b.HitTest.Void});
b.Sprite=b.DisplayObject.extend({init:function(a){b.DisplayObject.call(this,a);if(!this.source)throw Error("Invalid source property for Sprite");null===this.width&&(this.width=this.source.w);null===this.height&&(this.height=this.source.h)},paint:b.Paint.Sprite});b.Spritesheet=b.Class.extend({width:null,height:null,_sprites:null,init:function(a){switch(b.get_type(a)){case "string":case "dom":case "j5g3":a={source:a}}b.Class.call(this,a)},set source(a){switch(b.get_type(a)){case "string":case "dom":a=
new b.Image(a);break}if(!a)throw Error("Invalid source for Spritesheet.");null===this.width&&a&&(this.width=a.width);null===this.height&&a&&(this.height=a.height);this._source=a;this._sprites=[]},get source(){return this._source},select:function(a){var c=[];this.each(a,function(a){c.push(a)});return c},each:function(a,c){for(var b=0,e=a.length;b<e;b++)c(this.sprite(a[b]));return this},clip:function(a){var c=b.clip().remove_frame(),e=0,d=0;this.each(a,function(a){c.add_frame(a);a.width>e&&(e=a.width);
a.height>d&&(d=a.height)});return c.size(e,d).go(0)},push:function(a,c,b,e){this.slice(a,c,b,e);return this},slice:function(a,c,b,e){return this._sprites.push({width:b,height:e,source:{image:this.source.source,x:a,y:c,w:b,h:e}})-1},cut:function(a,c,b,e){return this.sprite(this.slice(a,c,b,e))},grid:function(a,c,b){b=b||0;var e=2*b,d=this.width/a-e|0,g=this.height/c-e|0,k,n;for(k=0;k<c;k++)for(n=0;n<a;n++)this.slice(n*(d+e)+b,k*(g+e)+b,d,g);return this},sprite:function(a){return new b.Sprite(this._sprites[a])},
sprites:function(){for(var a=0,c=this._sprites.length,b=[];a<c;a++)b.push(this.sprite(a));return b},map:function(a,c){return new b.Map({sprites:this.sprites(),tw:a,th:c})}});b.Emitter=b.Clip.extend({init:function(a){b.Clip.apply(this,[a])},source:b.Clip,container_update:function(){this._life--?null!==this._emitter_update&&this._emitter_update():this.remove()},life:10,on_emit:null,count:1,spawn:function(){var a=new this.source;a._life=this.life;a._emitter_update=a.update;a.update=this.container_update;
return a},_emit:function(){var a=this.spawn();this.add_object(a);if(this.on_emit)this.on_emit(a)},update_frame:function(){for(var a=this.count;a--;)this._emit()}});b.Map=b.DisplayObject.extend({sprites:null,map:null,tw:0,th:0,offsetX:0,offsetY:0,init:function(a){b.DisplayObject.apply(this,[a]);null===this.map&&(this.map=[])},to_iso:function(a,c){var b=(this.tw/2|0)+this.offsetX;return{x:(a*this.tw-(c%2?0:-b)|0)-this.cx,y:(c*((this.th/2|0)+this.offsetY)|0)-this.cy}},paint:b.Paint.Map});b.Action=b.Class.extend({_init:b.Class,
update:null,draw:b.Draw.Void,init:function(a){"function"===b.get_type(a)&&(a={update:a});this._init(a)},remove:b.DisplayObject.prototype.remove},{rotate:function(a){return function(){a.rotation=6.1>a.rotation?a.rotation+.1:0}}});b.Engine=b.Class.extend({version:"0.9.0",__fps:31,_renderLoopFn:null,_gameLoopFn:null,_renderLoopId:0,_gameLoopId:0,paused:!0,run:function(){var a=this;a.clear_process();a._renderLoopFn=function(){a._renderLoop()};a._renderLoop();a._gameLoopFn=function(){a._gameLoop()};a._gameLoopId=
d.setInterval(a._gameLoopFn,a.__fps);a.paused=!1;return a},clear_process:function(){d.clearInterval(this._gameLoopId);d.cancelAnimationFrame(this._renderLoopId)},destroy:function(){this.pause();if(this.on_destroy)this.on_destroy()},_renderLoop:function(){this.stage.draw();this._renderLoopId=d.requestAnimationFrame(this._renderLoopFn)},_gameLoop:function(){this.stage.update()},startFn:function(){},init:function(a){"function"===typeof a&&(a={startFn:a});a===e&&(a={});c.style.display="none";c.setAttribute("id",
"j5g3-cache");d.document.body.appendChild(c);b.Class.apply(this,[a]);this.stage_settings||(this.stage_settings={});this.stage_settings.canvas||(this.stage_settings.canvas=b.id("screen"));this.stage||(this.stage=new b.Stage(this.stage_settings));this.startFn(b,this)},pause:function(){this.clear_process();this._renderLoopFn=function(){};this.paused=!0},resume:function(){this.paused&&this.run()},set fps(a){this.__fps=1E3/a},get fps(){return 1E3/this.__fps},imagedata:function(a,e){var d,g;switch(b.get_type(a)){case "string":d=
b.id(a);break;case "dom":d=a;break;case "j5g3":d=a.source}return d?(c.width=d.width,c.height=d.height,g=c.getContext("2d"),g.drawImage(d,0,0),g.getImageData(0,0,d.width,d.height)):this.stage.context.createImageData(a||this.stage.canvas.width,e||this.stage.canvas.height)}});b.Easing=function(){var a={},c,b={},e=function(a,c){b["EaseIn"+a]=c;b["EaseOut"+a]=function(a){return 1-c(1-a)};b["EaseInOut"+a]=function(a){return.5>a?c(2*a)/2:c(-2*a+2)/-2+1}};["Quad","Cubic","Quart","Quint","Expo"].forEach(function(c,
b){a[c]=function(a){return Math.pow(a,b+2)}});a.Sine=function(a){return 1-Math.cos(a*Math.PI/2)};a.Circ=function(a){return 1-Math.sqrt(1-a*a)};a.Elastic=function(a){return 0===a||1===a?a:-Math.pow(2,8*(a-1))*Math.sin((80*(a-1)-7.5)*Math.PI/15)};a.Back=function(a){return a*a*(3*a-2)};a.Bounce=function(a){for(var c,b=4;a<((c=Math.pow(2,--b))-1)/11;);return 1/Math.pow(4,3-b)-7.5625*Math.pow((3*c-2)/22-a,2)};for(c in a)e(c,a[c]);b.Linear=function(a){return a};b.Swing=function(a){return-Math.cos(a*Math.PI)/
2+.5};return b}();b.action=g(b.Action);b.clip=g(b.Clip);b.image=g(b.Image);b.sprite=g(b.Sprite);b.spritesheet=g(b.Spritesheet);b.text=g(b.Text);b.stage=g(b.Stage);b.mtext=function(a){a=new b.Text(a);a.paint=b.Paint.MultilineText;return a};b.matrix=function(a,c,e,d,g,p){return new b.Matrix(a,c,e,d,g,p)};b.tween=g(b.Tween);b.emitter=g(b.Emitter);b.map=g(b.Map);b.html=g(b.Html);b.engine=g(b.Engine)})(this,this.j5g3);
(function(d,b,e){b.Loader=b.Class.extend({EVENT:{IMG:"load",AUDIO:"canplaythrough",SCRIPT:"load"},sources:null,delay:250,progress:0,start:null,length:0,on_progress:null,on_source:null,on_ready:null,init:function(c){b.Class.apply(this,[c]);this.sources={};this.start=new Date},_check_ready:function(){var c,b=0,a=0,e=this;for(c in this.sources)a++,this.sources.hasOwnProperty(c)&&this.sources[c].ready&&b++;this.progress=b?b/a:0;if(this.on_progress)this.on_progress(this.progress);if(a===b){if(this.on_ready)this.on_ready()}else this._timeout=
d.setTimeout(function(){e._check_ready()},this.delay)},el:function(c,e){var a=this,f=this.sources[e],h;f?f=f.el:(f=b.dom(c),this.sources[e]=h={el:f},f.addEventListener(this.EVENT[c],function(){h.ready=!0;if(a.on_source)a.on_source(h)},!1),f.addEventListener("error",function(){h.ready=!0;d.console.warn("Could not load asset: "+e)},!1),f.setAttribute("src",e),this.length++);return f},img:function(c){return this.el("IMG",c)},audio:function(c){var e=c.split(".").pop();b.support.audio[e]||(c=c.replace(new RegExp("\\."+
e+"$"),"."+b.support.audio.preferred));return this.el("AUDIO",c)},data:function(c,b){var a=this,e=new d.XMLHttpRequest,h=this.sources[c];h||(h=this.sources[c]={source:c,request:e},e.onreadystatechange=function(){if(4===e.readyState&&(h.ready=!0,h.raw=e.responseText,b&&b(h),a.on_source))a.on_source(e)},e.open("GET",c),e.send());return h},json:function(c){return this.data(c,function(c){c.json=JSON.parse(c.raw)})},script:function(c){c=this.el("SCRIPT",c);d.document.head.appendChild(c);return c},ready:function(c){c&&
(this.on_ready=c);this._check_ready()},destroy:function(){d.clearTimeout(this._timeout)}});b.loader=b.factory(b.Loader)})(this,this.j5g3);
(function(d,b){d.Collision=d.Class.extend({A:null,B:null,nx:0,ny:0,penetration:0,length:0,tx:0,ty:0,0:null,1:null,2:null,3:null,4:null,5:null,6:null,query:null});d.Collision.Circle=d.Collision.extend({query:function(b,c){var d=b.radius+c.radius,a=b.x+b.radius+b.cx,f=b.y+b.radius+b.cy,h=a-c.radius-c.cx-c.x,l=f-c.radius-c.cy-c.y,m=h*h+l*l;if(this.collides=d*d>m)return m=Math.sqrt(m),this.A=b,this.B=c,this.nx=h/m,this.ny=l/m,this.penetration=d-m,this[0]=a-h/2,this[1]=f-l/2,!0}});d.Collision.AABB=d.Collision.extend({query:function(b,
c){var d=b.x+b.cx,a=c.x+c.cx,f=b.y+b.cy,h=c.y+c.cy,l=d+b.width,m=a+c.width,p=f+b.height,k=h+c.height,n,q;if(this.collides=!(a>=l||m<=d||h>=p||k<=f))return this.B=c,n=this.tx=m/2-l/2,q=this.ty=k/2-p/2,this[0]=Math.max(d,a),this[1]=Math.max(f,h),this[2]=Math.min(l,m),this[3]=Math.min(p,k),this[2]-this[0]<this[3]-this[1]?(this.nx=0>n?-1:1,this.ny=0,this.penetration=0>n?this[2]-d:l-this[0]):(this.ny=0>q?-1:1,this.nx=0,this.penetration=0>q?this[3]-f:p-this[1]),this}});d.CollisionTest={Circle:function(b){var c=
this.radius+b.radius,d=this.x+this.radius+this.cx-b.radius-b.cx-b.x;b=this.y+this.radius+this.cy-b.radius-b.cy-b.y;return c*c>d*d+b*b},AABB:function(b){var c=this.y+this.height,d=b.x+b.width,a=b.y+b.height;return!(b.x>this.x+this.width||d<this.x||b.y>c||a<this.y)},Container:function(b){var c=this.frame,d=c,a=!1;for(b={x:b.x-this.x,y:b.y-this.y,width:b.width,height:b.height};(d=d._previous)!==c&&!(a=d.collides&&d.collides(b)););return a}};d.DisplayObject.prototype.collides=d.CollisionTest.AABB;d.Clip.prototype.collides=
d.CollisionTest.Container})(this.j5g3);
(function(d,b){d.Shape=d.DisplayObject.extend({shape:null,red:b,green:b,blue:b,color_property:"fill",_red:b,_green:b,_blue:b,line_width:null,init:function(b){d.DisplayObject.apply(this,[b])},_begin:d.DisplayObject.prototype.begin,begin:function(b){if(this.red!==this._red||this.blue!==this._blue||this.green!==this._green)this[this.color_property]="rgb("+Math.floor(this.red)+","+Math.floor(this.green)+","+Math.floor(this.blue)+")",this._red=this._red,this._green=this.green,this._blue=this.blue;this._begin(b)},
paintPath:function(){},paint:function(b){b.beginPath();this.paintPath(b);b.closePath();b.fill();b.stroke()}});d.Circle=d.Shape.extend({shape:"circle",radius:0,init:function(b){"number"===typeof b&&(b={radius:b});d.Shape.apply(this,[b])},paintPath:function(b){b.arc(this.radius+this.cx,this.radius+this.cy,this.radius,0,2*Math.PI,!1)},at:d.HitTest.Circle});d.Line=d.Shape.extend({x2:0,y2:0,paintPath:function(b){b.moveTo(this.cx,this.cy);b.lineTo(this.x2,this.y2)}});d.Polygon=d.Shape.extend({shape:"polygon",
points:null,normals:null,init:function(b){d.Shape.apply(this,[b]);null===this.points&&(this.points=[]);null===this.normals&&this.calculate_normals()},normalize:function(b){var c=Math.sqrt(b[0]*b[0]+b[1]*b[1]);b[0]/=c;b[1]/=c;return b},calculate_normals:function(){for(var b=0,c,d=this.points,a=d.length,f=[],h=[0,0];b<a;b+=2)c=b+2<a?b+2:0,h[0]=d[c]-d[b],h[1]=d[c+1]-d[b+1],this.normalize(h),f.push(h[1],-h[0]);this.normals=f},paintPath:function(b){var c=2,d=this.points,a=d.length;for(b.moveTo(d[0],d[1]);c<
a;c+=2)b.lineTo(d[c],d[c+1])},at:d.HitTest.Polygon},{create:function(b,c){var g=2*Math.PI/b,a=g;for(c.points=[];b--;)c.points.push(Math.cos(a)*c.radius,Math.sin(a)*c.radius),a+=g;return new d.Polygon(c)}});d.Rect=d.Shape.extend({shape:"polygon",init:function(b){d.Shape.apply(this,[b]);null===this.width&&(this.height=this.width=2*this.radius)},paint:function(b){b.fillRect(this.cx,this.cy,this.width,this.height);b.strokeRect(this.cx,this.cy,this.width,this.height)}});d.Dot=d.Shape.extend({shape:"circle",
line_cap:"round",line_join:"round",color_property:"stroke",init:function(b){"number"===typeof b&&(b={line_width:b});d.Shape.apply(this,[b])},paint:function(b){b.strokeRect(0,0,1,1)}});d.polygon=d.factory(d.Polygon);d.circle=d.factory(d.Circle);d.line=d.factory(d.Line);d.dot=d.factory(d.Dot);d.rect=d.factory(d.Rect)})(this.j5g3);
(function(d,b){var e=b.dom("audio"),c=["wav","mp3","ogg"],g=["audio/wav","audio/mpeg","audio/ogg"];Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}});d.HTMLAudioElement||(d.HTMLAudioElement=d.Audio);d.requestAnimationFrame||(d.requestAnimationFrame=d.mozRequestAnimationFrame||d.msRequestAnimationFrame||function(a){return d.setTimeout(a,1E3/60)});d.cancelAnimationFrame||(d.cancelAnimationFrame=d.mozCancelAnimationFrame||d.msCancelAnimationFrame||
function(a){d.clearTimeout(a)});b.support={audio:{},touch:"ontouchstart"in d.document};e&&e.canPlayType&&c.forEach(function(a,c){b.support.audio[a]=e.canPlayType(g[c]);b.support.audio[a]&&(b.support.audio.preferred=a)})})(this,this.j5g3);(function(d,b,e){d.in=function(c){return new d.in.Listener(c)};d.extend(d.in,{Modules:{},Listener:d.Class.extend({x:0,y:0,dx:0,dy:0,sx:1,sy:1,module:null,element:null,interval:60,intervalId:null,handlers:null,minimal:!1,disabled:!1,init:function(c){var e=this;if("string"===typeof c||"object"===typeof c&&c.tagName)c={element:c};d.Class.call(this,c);null===this.element?this.element=b.document:"string"===typeof this.element&&(this.element=d.id(this.element));e.module={};e.handlers={};e.poll=function(){e._poll()};
e.calculate_bound=function(a){e._calculate_bound(a)};b.addEventListener("resize",this.calculate_bound);b.addEventListener("scroll",this.calculate_bound);this.intervalId=b.setInterval(this.poll,this.interval);this.calculate_bound();for(var a in d.in.Modules)e.module[a]=new d.in.Modules[a](e)},suspend:function(c){var d=this;d.disabled=!0;b.setTimeout(function(){d.disabled=!1},c)},on:function(c,b){if("object"===typeof c)for(var a in c)this.on(a,c[a]);else{if(!b)throw Error("callback parameter is required.");
var d=this.handlers[c];this.handlers[c]=d?function(a){d(a);b(a)}:b}return this},fire:function(c,b){if(!this.disabled&&(b.j5g3in=this,b.name=c,(!this.on_fire||!1!==this.on_fire(b))&&this.handlers[c]))return b.preventDefault(),this.handlers[c](b)},_calculate_bound:function(){var c=this.element;c.getBoundingClientRect?(c=c.getBoundingClientRect(),this.bx=b.scrollX+c.left||0,this.by=b.scrollY+c.top||0):(this.bx=c.clientLeft||0,this.by=c.clientTop||0)},_poll:function(){if(!1===this.disabled)for(var c in this.module)this.module[c].update()},
set_pos:function(c,b){c=c*this.sx-this.bx;b=b*this.sy-this.by;this.dx=c-this.x;this.dy=b-this.y;this.x=c;this.y=b},destroy:function(){this.disable();this.handlers=null;b.removeEventListener("scroll",this.calculate_bound);b.removeEventListener("resize",this.calculate_bound);b.clearInterval(this.poll)},enable:function(){this.disabled=!1;for(var c in this.module)this.module[c].enable()},disable:function(){this.disabled=!0;for(var c in this.module)this.module[c].disable()}}),Module:d.Class.extend({handler:null,
el:null,enabled:!1,_enable:null,_disable:null,init:function(c){this.handler={};this.listener=c;this.el=c.element;this.enable();c.minimal&&this._minimal()},update:function(){},_on:function(c,b){var a=b.bind(this);this.handler[c]=a;this.el.addEventListener(c,a)},_un:function(c){this.el.removeEventListener(c,this.handler[c])},enable:function(){this.enabled||(this._enable(),this.enabled=!0);return this},disable:function(){this.enabled&&(this._disable(),this.enabled=!1);return this},destroy:function(){this.disable();
for(var c in this.listener.module)if(this.listener.module[c]===this){delete this.listener.module[c];break}}}),Button:d.Class.extend({init:function(c){d.Class.call(this,c)}})})})(this.j5g3,this);
(function(d,b,e){d.in.Modules.Mouse=d.in.Module.extend({x_threshold:1,y_threshold:1,bx:0,by:0,capture_move:!0,_calculate_pos:function(c){this.listener.set_pos(c.pageX,c.pageY)},_click:function(c){var b={0:"buttonY",1:"buttonX",2:"buttonA"}[c.button];this._calculate_pos(c);this.listener.fire(b,c);this.listener.fire("button",c);return!1},_minimal:function(){this.capture_move=!1},_mousemove:function(c){this.capture_move&&(this._calculate_pos(c),(Math.abs(this.listener.dx)>this.x_threshold||Math.abs(this.listener.dy)>
this.y_threshold)&&this.listener.fire("move",c))},_enable:function(){this._on("mousemove",this._mousemove);this._on("click",this._click);this._on("contextmenu",this._click)},_disable:function(){this._un("mousemove");this._un("click");this._un("contextmenu")}})})(this.j5g3,this);
(function(d,b,e){d.in.Modules.Touch=d.in.Module.extend({x_threshold:20,y_threshold:20,flick_threshold:70,flick_delay:350,tap_delay:350,touches:null,move_type:"linear",radius:25,angle:0,_calculate_pos:function(c){this.listener.set_pos(c.pageX,c.pageY)},each_touch:function(c,b){for(var a=c.changedTouches,d=a.length,e,l;d--;)l=a[d].identifier,e=this.touches[l]||(this.touches[l]={id:l}),e.ev=c,e.touch=a[l],this._calculate_pos(a[d]),b(c,a[d],e,this)},update:function(){var c=this.touches,b;for(b in c)this.listener.set_pos(c[b].mx,
c[b].my),this.listener.fire("buttonY",c[b].ev),this.listener.fire("button",c[b].ev)},__touchmove:function(c,b,a,d){b=d.listener.x;var e=d.listener.y,l=b-a.mx,m=e-a.my,p=Date.now()-a.touchstart_t,k;l<-d.x_threshold?(a.mx=b,k="left"):l>d.x_threshold&&(a.mx=b,k="right");m<-d.y_threshold?(a.my=e,k="up"+(k?"_"+k:"")):m>d.y_threshold&&(a.my=e,k="down"+(k?"_"+k:""));(d.direction=k)&&p>d.flick_delay&&(d.listener.fire(k,c),d.listener.fire("move",c))},__touchradial:function(c,b,a,d){var e=d.listener.x,l=d.listener.y;
b=a.tx-e;var m=a.ty-l,e=e-a.pivotx;a=l-a.pivoty;(b>d.x_threshold||b<-d.x_threshold)&&(m>d.y_threshold||m<-d.y_threshold)&&(c.angle=Math.atan2(a,e),d.listener.fire("move",c))},_touchmove:function(c){this.each_touch(c,"linear"===this.move_type?this.__touchmove:this.__touchradial)},_flick_action:function(c,b){var a=this.listener.x-b.tx,d=this.listener.y-b.ty,e;a<-this.flick_threshold?e="buttonY":a>this.flick_threshold&&(e="buttonA");d<-this.flick_threshold?e="buttonX":d>this.flick_threshold&&(e="buttonB");
e?this.listener.fire(e,c):this.direction&&(this.listener.fire(this.direction,c),this.listener.fire("move",c))},set_pivot:function(c){c.pivotx=c.tx-Math.cos(this.angle)*this.radius;c.pivoty=c.ty-Math.sin(this.angle)*this.radius},__touchstart:function(c,b,a,d){a.touchstart_t=Date.now();a.ev=c;a.tx=a.mx=d.listener.x;a.ty=a.my=d.listener.y;"radial"===d.move_type&&d.set_pivot(a)},_touchstart:function(c){this.direction=!1;this.each_touch(c,this.__touchstart)},__touchend:function(c,b,a,d){b=Date.now()-a.touchstart_t;
!d.direction&&b<d.tap_delay?d.listener.fire("buttonY",c):b<d.flick_delay&&d._flick_action(c,a);delete d.touches[a.id]},_touchend:function(c){this.each_touch(c,this.__touchend)},_enable:function(){this._on("touchmove",this._touchmove);this._on("touchstart",this._touchstart);this._on("touchend",this._touchend);this.touches={}},_disable:function(){this._un("touchmove");this._un("touchstart");this._un("touchend")}})})(this.j5g3,this);
(function(d,b,e){var c=b.document,g={32:"buttonB",13:"buttonY",16:"buttonX",17:"buttonA",37:"left",38:"up",39:"right",40:"down",105:"up_right",103:"up_left",99:"down_right",97:"down_left"};d.in.Modules.Keyboard=d.in.Module.extend({keymap:null,keys:null,_keydown:function(a){this.keys[a.keyCode]=a;this.keymap[a.keyCode]&&a.preventDefault()},init:function(a){this.keys={};d.in.Module.call(this,a);null===this.keymap&&d.extend(this.keymap={},g)},_keyup:function(a){this.keys[a.keyCode]=!1},update:function(){var a,
c,b;for(b in this.keymap)if(c=this.keys[b])a=this.keymap[b],this.listener.fire(a,c),32<b&&(c.direction=a,this.listener.fire("move",c)),this.listener.fire("button",c)},_enable:function(){this.keys={};this.handler.keydown=this._keydown.bind(this);this.handler.keyup=this._keyup.bind(this);c.addEventListener("keydown",this.handler.keydown);c.addEventListener("keyup",this.handler.keyup)},_disable:function(){this.keys={};c.removeEventListener("keydown",this.handler.keydown);c.removeEventListener("keyup",
this.handler.keyup)}})})(this.j5g3,this);(function(d,b,e){b.navigator.webkitGetGamepads&&(d.in.Modules.Joystick=d.in.Module.extend({_enable:function(){},_disable:function(){}}))})(this.j5g3,this);(function(d,b){d.fx={Resources:{diamond:d.dom.image("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPxJREFUeNqckzEKwjAUhlPB6hm8QUd1EbpVRHAS0eO0N3DuIVx0EaSoHbtoR2/gFVorGv/oSwnRIfHBlwba/Pnf63sO53zDGLuCNdgxs/DAAvQZBCL+iQfIwRL4gGl4IAQpKOlM7IgXUMpBS7nhDs4gARUIwAC0lW+eYCLVU24fwi1rkNqe2cfhvSr5FRa3V7JOapGOFgKZPNf4smQWidyoAq6FQPVLYGQhENQ7ysWnwphGQYWvHcxA08KBaKi5mkLwRx8MxSJaeYznVqtHCTL6My7Vp6e5vIGuyD+mvEpq6VDmp+HToOU0eCIih8b5BFbgYmhfuJ6CzkuAAQBw8IUZ2uqgnAAAAABJRU5ErkJggg=="),
star:d.dom.image("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAO5JREFUeNpi/P//PwMeEA3EL4B4Ly4FjAQM2APEH4E4GKcKkAE4sD0Q/wXi30BshEsdEx7b04AYJM8CxDmkukANiL/+R4DPQKyCTS0oDJKA5kgBsTgSlodiZPAIiB8C8WsgfgnEr4D4KcgUbyB+/Z908AKInWBOMQXiOyRovgXE+uAYRPKPIhCfIULzKSCWg+lDDxRhIL6LR/NDIBbEF42fgVgIT9SKgiIOWQDdAEsgFsBjACcQW+AzwADNNZ1A3AjE75DEDfElpPnQ5Lscmphg4rJAPAeIfwHxKmQ96AYsBGJnPPkDFN0LkMUAAgwAJMvR40MRRPUAAAAASUVORK5CYII=")},Particles:{Dust:function(){}},
Blending:{Glow:function(){}},Text:{Neon:function(b){var c=this.stroke||this.fill||b.fillStyle,d=this.line_width||b.lineWidth;b.strokeStyle=c;b.globalAlpha=.2;b.lineWidth=d+10;b.strokeText(this.text,this.cx,this.cy);b.globalAlpha=.4;b.lineWidth=d+5;b.strokeText(this.text,this.cx,this.cy);b.globalAlpha=1;b.lineWidth=d;b.strokeText(this.text,this.cx,this.cy);b.globalCompositeOperation="lighter";b.fillStyle=c;b.fillText(this.text,this.cx,this.cy)},Mirror:function(b){this._paint(b);b.scale(1,-1);var c=
this.cy;this.cy-=2*this.line_height;this.gradient||(this.gradient=b.createLinearGradient(-this.cx,this.cy,-this.cx,this.cy+this.line_height),this.gradient.addColorStop(1,this.fill||b.fillStyle),this.gradient.addColorStop(0,"transparent"));b.fillStyle=this.gradient;this._paint(b);this.cy=c}},Animate:{fade_in:function(b){return new d.Tween({target:b,duration:30,auto_remove:!0,from:{alpha:0},to:{alpha:1}})},fade_out:function(b){return new d.Tween({target:b,auto_remove:!0,duration:30,to:{alpha:0}})},
expand:function(b,c){c=c||1.5;return new d.Tween({target:b,auto_remove:!0,duration:30,to:{sx:b.sx+c,sy:b.sy+c}})},shake:function(b){b=new d.Tween({target:b,radius:3,duration:10,auto_remove:!0,to:{x:b.x,y:b.y}});b.apply_tween=function(b,e){return 1===e?this.to[b]:this.from[b]-this.radius+d.rand(2*this.radius)};return b}}}})(this.j5g3);
